-- db/extras/taxonomy_seed_bora_cuiaba.sql
--
-- Seed da taxonomia do Bora Cuiabá (plugin taxonomy): grupo -> categoria -> subcategoria -> tag.
-- Conteúdo específico deste projeto — por isso fica em db/extras/ e não no plugin do core.
--
--   15 grupos · 56 categorias · 206 subcategorias · 840 tags · 21 vínculos extras
--
-- Pré-requisitos: schema do core + plugin taxonomy aplicados, e um usuário root já cadastrado
-- (tenant_id/created_by vêm do primeiro root e do tenant dele, igual ao seed de páginas; sem root,
-- cada INSERT vira no-op silencioso).
--
-- Idempotente: pode rodar de novo. Grupos, categorias e subcategorias são casados pelo slug e
-- têm nome/descrição/ícone atualizados; tags são casadas por (subcategoria, slug). Nada é apagado.
--
-- Aplicar:
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/extras/taxonomy_seed_bora_cuiaba.sql
--   (Docker: docker exec -i <container> psql -U <user> -d <db> -v ON_ERROR_STOP=1 < db/extras/taxonomy_seed_bora_cuiaba.sql)

BEGIN;

-- 1) Grupos ------------------------------------------------------------------------------------
INSERT INTO public.categories_group (name, slug, description, tags, icon, sort_order, active, tenant_id, created_by)
SELECT v.name, v.slug, v.description, v.tags, v.icon, v.sort_order, true, t.uid, u.uid
FROM (VALUES
    ('Eventos', 'eventos', 'Agenda do que rola em Cuiabá e região: shows, festas, festivais e encontros.', 'agenda, programação, hoje, fim de semana, ingresso', 'CalendarDays', 10),
    ('Cinema & Teatro', 'cinema-e-teatro', 'Filmes em cartaz, peças, stand-up e espetáculos de palco.', 'filme, sessão, peça, espetáculo, stand-up', 'Clapperboard', 20),
    ('Trilhas & Aventura', 'trilhas-e-aventura', 'Trilhas, esportes de aventura e mirantes na Chapada, no Pantanal e arredores.', 'trilha, aventura, ecoturismo, chapada, natureza', 'Mountain', 30),
    ('Camping & Natureza', 'camping-e-natureza', 'Camping, cachoeiras, rios, parques e a vida selvagem do cerrado e do Pantanal.', 'camping, natureza, cachoeira, rio, pantanal', 'Tent', 40),
    ('Bares & Vida Noturna', 'bares-e-vida-noturna', 'Botecos, choperias, drinks e baladas para a noite cuiabana.', 'bar, boteco, chope, drinks, noite, balada', 'Beer', 50),
    ('Restaurantes & Gastronomia', 'restaurantes-e-gastronomia', 'Da peixada cuiabana à alta gastronomia: onde comer bem na região.', 'restaurante, comida, almoço, jantar, gastronomia, culinária', 'UtensilsCrossed', 60),
    ('Turismo', 'turismo', 'Pontos turísticos de Cuiabá e os destinos imperdíveis ao redor: Chapada, Pantanal e Nobres.', 'turismo, passeio, viagem, ponto turístico, roteiro', 'MapPinned', 70),
    ('Notícias', 'noticias', 'O que está acontecendo na cidade, na cultura, no turismo e no esporte.', 'notícias, novidades, cidade, informação, atualidades', 'Newspaper', 80),
    ('Cultura & Arte', 'cultura-e-arte', 'Exposições, artesanato, cultura popular e espaços culturais.', 'cultura, arte, exposição, artesanato, folclore', 'Palette', 90),
    ('Esportes & Lazer', 'esportes-e-lazer', 'Corrida, pedal, esportes aquáticos, jogos e diversão ao ar livre.', 'esporte, lazer, corrida, pedal, jogo, diversão', 'Bike', 100),
    ('Família & Crianças', 'familia-e-criancas', 'Passeios, programação infantil e lugares que recebem bem os pequenos.', 'criança, família, infantil, passeio, kids', 'Baby', 110),
    ('Compras & Feiras', 'compras-e-feiras', 'Feiras, shoppings, produtos regionais e marcas locais.', 'compras, feira, shopping, artesanato, loja', 'ShoppingBag', 120),
    ('Hospedagem', 'hospedagem', 'Onde ficar em Cuiabá, na Chapada e no Pantanal.', 'hotel, pousada, hospedagem, chalé, day use', 'BedDouble', 130),
    ('Bem-estar', 'bem-estar', 'Spas, yoga, meditação e atividade física para recarregar.', 'bem-estar, saúde, spa, yoga, relaxar', 'Flower2', 140),
    ('Dicas & Roteiros', 'dicas-e-roteiros', 'Roteiros prontos, dicas práticas e achados locais para curtir melhor a região.', 'dicas, roteiro, guia, o que fazer, achados', 'Lightbulb', 150)
) AS v(name, slug, description, tags, icon, sort_order)
JOIN LATERAL (
    SELECT uid FROM auth.users WHERE is_root = true ORDER BY created_at ASC LIMIT 1
) AS u(uid) ON true
JOIN LATERAL (
    SELECT tn.uid FROM auth.tenants tn WHERE tn.owner_uid = u.uid ORDER BY tn.created_at ASC LIMIT 1
) AS t(uid) ON true
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, tags = EXCLUDED.tags,
  icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order, updated_at = now();

-- 2) Categorias (grupo "casa" em category_group_id) --------------------------------------------
INSERT INTO public.categories (category_group_id, name, slug, description, icon, active, tenant_id, created_by)
SELECT g.id, v.name, v.slug, v.description, v.icon, true, t.uid, u.uid
FROM (VALUES
    ('eventos', 'Shows & Música ao Vivo', 'shows-e-musica-ao-vivo', 'Apresentações musicais de todos os estilos, dos grandes palcos aos barzinhos.', 'Music'),
    ('eventos', 'Festas & Baladas', 'festas-e-baladas', 'Festas, baladas e celebrações para curtir a noite.', 'PartyPopper'),
    ('eventos', 'Festas Tradicionais & Religiosas', 'festas-tradicionais-e-religiosas', 'Festas populares, de santo e datas que fazem parte da identidade cuiabana.', 'Church'),
    ('eventos', 'Festivais & Exposições', 'festivais-e-exposicoes', 'Festivais, exposições agropecuárias e grandes eventos com vários dias de programação.', 'Ticket'),
    ('eventos', 'Palestras & Encontros', 'palestras-e-encontros', 'Eventos de conhecimento, networking e comunidade.', 'Presentation'),
    ('cinema-e-teatro', 'Cinema', 'cinema', 'Estreias, mostras e sessões especiais nas telas da cidade.', 'Film'),
    ('cinema-e-teatro', 'Teatro', 'teatro', 'Peças, musicais e teatro para todas as idades.', 'Drama'),
    ('cinema-e-teatro', 'Humor & Espetáculos', 'humor-e-espetaculos', 'Stand-up, circo, dança e espetáculos de palco.', 'Laugh'),
    ('trilhas-e-aventura', 'Trilhas', 'trilhas', 'Trilhas por nível de dificuldade, com e sem cachoeira.', 'Footprints'),
    ('trilhas-e-aventura', 'Esportes de Aventura', 'esportes-de-aventura', 'Adrenalina com rapel, flutuação, tirolesa e pedal.', 'Zap'),
    ('trilhas-e-aventura', 'Mirantes & Formações', 'mirantes-e-formacoes', 'Mirantes, cavernas e formações rochosas para ver de perto.', 'Binoculars'),
    ('trilhas-e-aventura', 'Guias & Agências', 'guias-e-agencias', 'Quem leva você com segurança: guias, passeios e transporte.', 'Compass'),
    ('camping-e-natureza', 'Camping', 'camping', 'Do camping raiz ao glamping com conforto.', 'Tent'),
    ('camping-e-natureza', 'Cachoeiras & Rios', 'cachoeiras-e-rios', 'Banho de cachoeira, prainhas de rio e balneários.', 'Waves'),
    ('camping-e-natureza', 'Pantanal & Vida Selvagem', 'pantanal-e-vida-selvagem', 'Observação de fauna, pesca esportiva e passeios de barco no Pantanal.', 'Bird'),
    ('camping-e-natureza', 'Parques & Áreas Verdes', 'parques-e-areas-verdes', 'Parques urbanos, parques estaduais e nacionais para caminhar e respirar.', 'Trees'),
    ('bares-e-vida-noturna', 'Bares', 'bares', 'Do boteco raiz ao rooftop com vista.', 'Beer'),
    ('bares-e-vida-noturna', 'Drinks & Destilados', 'drinks-e-destilados', 'Coquetelaria, adegas e cachaçarias.', 'Martini'),
    ('bares-e-vida-noturna', 'Baladas & Casas Noturnas', 'baladas-e-casas-noturnas', 'Pista, DJ, sertanejo, forró e karaokê.', 'Disc3'),
    ('bares-e-vida-noturna', 'Happy Hour & Petiscos', 'happy-hour-e-petiscos', 'Promoções de fim de tarde, porções e espetinhos.', 'Clock'),
    ('restaurantes-e-gastronomia', 'Culinária Cuiabana & Pantaneira', 'culinaria-cuiabana-e-pantaneira', 'Os sabores de Mato Grosso: peixes de rio, pequi, banana-da-terra e doces típicos.', 'Fish'),
    ('restaurantes-e-gastronomia', 'Restaurantes', 'restaurantes', 'Churrascarias, cozinha contemporânea, internacional e almoço do dia a dia.', 'Utensils'),
    ('restaurantes-e-gastronomia', 'Cafés & Docerias', 'cafes-e-docerias', 'Café especial, padarias, confeitarias e sorvetes para o calor cuiabano.', 'Coffee'),
    ('restaurantes-e-gastronomia', 'Lanches & Delivery', 'lanches-e-delivery', 'Hambúrguer, pizza, comida de rua e delivery a qualquer hora.', 'Sandwich'),
    ('turismo', 'Cuiabá', 'cuiaba', 'O que visitar na capital: centro histórico, museus, orla e mirantes.', 'Landmark'),
    ('turismo', 'Chapada dos Guimarães', 'chapada-dos-guimaraes', 'Cachoeiras, mirantes e a vila charmosa da Chapada, a 65 km de Cuiabá.', 'MountainSnow'),
    ('turismo', 'Pantanal', 'pantanal', 'A maior planície alagável do planeta, com porta de entrada por Poconé e Barão de Melgaço.', 'Leaf'),
    ('turismo', 'Nobres & Arredores', 'nobres-e-arredores', 'Águas cristalinas, rafting e cidades próximas para bate-volta.', 'Droplets'),
    ('turismo', 'Passeios & Roteiros', 'passeios-e-roteiros', 'City tours, bate-voltas e turismo rural.', 'Route'),
    ('noticias', 'Cidade', 'cidade', 'Notícias do dia a dia de Cuiabá e Várzea Grande.', 'Building2'),
    ('noticias', 'Cultura & Entretenimento', 'cultura-e-entretenimento', 'Novidades do entretenimento local.', 'Megaphone'),
    ('noticias', 'Meio Ambiente & Clima', 'meio-ambiente-e-clima', 'Clima, queimadas, parques e regras de pesca.', 'CloudSun'),
    ('noticias', 'Esportes', 'esportes', 'Futebol mato-grossense, corridas e eventos esportivos.', 'Trophy'),
    ('cultura-e-arte', 'Exposições & Galerias', 'exposicoes-e-galerias', 'Arte visual em galerias, museus e nas ruas.', 'Frame'),
    ('cultura-e-arte', 'Cultura Popular & Artesanato', 'cultura-popular-e-artesanato', 'A cultura que faz de Cuiabá, Cuiabá: viola de cocho, siriri, cururu e cerâmica.', 'Brush'),
    ('cultura-e-arte', 'Espaços Culturais', 'espacos-culturais', 'Centros culturais, bibliotecas, livrarias e saraus.', 'Library'),
    ('cultura-e-arte', 'Cursos & Oficinas', 'cursos-e-oficinas', 'Aprender algo novo: arte, música, dança e cozinha.', 'GraduationCap'),
    ('esportes-e-lazer', 'Corrida & Ciclismo', 'corrida-e-ciclismo', 'Provas de rua, grupos de corrida e pedais pela cidade.', 'PersonStanding'),
    ('esportes-e-lazer', 'Esportes Aquáticos', 'esportes-aquaticos', 'SUP, caiaque, natação e clubes com piscina.', 'Sailboat'),
    ('esportes-e-lazer', 'Jogos & Estádios', 'jogos-e-estadios', 'Onde assistir e praticar: futebol, quadras, lutas e games.', 'Goal'),
    ('esportes-e-lazer', 'Diversão ao Ar Livre', 'diversao-ao-ar-livre', 'Parques aquáticos, pesque-pague, kart e muito mais.', 'Sun'),
    ('familia-e-criancas', 'Passeios em Família', 'passeios-em-familia', 'Programas para todas as idades.', 'Users'),
    ('familia-e-criancas', 'Programação Infantil', 'programacao-infantil', 'Teatro, oficinas, festas e férias para crianças.', 'Blocks'),
    ('familia-e-criancas', 'Restaurantes para Crianças', 'restaurantes-para-criancas', 'Onde comer com tranquilidade levando as crianças.', 'IceCreamCone'),
    ('compras-e-feiras', 'Feiras', 'feiras', 'Feiras livres, de artesanato, orgânicas e brechós.', 'Store'),
    ('compras-e-feiras', 'Shoppings & Lojas', 'shoppings-e-lojas', 'Shoppings, lembranças de viagem e empórios regionais.', 'ShoppingCart'),
    ('compras-e-feiras', 'Moda & Design Local', 'moda-e-design-local', 'Marcas, ateliês e bazares de criadores mato-grossenses.', 'Shirt'),
    ('hospedagem', 'Hotéis & Pousadas', 'hoteis-e-pousadas', 'Hotéis, pousadas e hotéis-fazenda.', 'Hotel'),
    ('hospedagem', 'Hospedagem Alternativa', 'hospedagem-alternativa', 'Chalés, hostels e casas de temporada.', 'House'),
    ('hospedagem', 'Day Use', 'day-use', 'Aproveite a estrutura sem precisar dormir.', 'Umbrella'),
    ('bem-estar', 'Spas & Relaxamento', 'spas-e-relaxamento', 'Massagens, termas e dias de spa.', 'Sparkles'),
    ('bem-estar', 'Yoga & Meditação', 'yoga-e-meditacao', 'Práticas para o corpo e a mente, inclusive ao ar livre.', 'Heart'),
    ('bem-estar', 'Atividade Física', 'atividade-fisica', 'Academias, estúdios e treinos ao ar livre.', 'Dumbbell'),
    ('dicas-e-roteiros', 'Roteiros Prontos', 'roteiros-prontos', 'Roteiros testados para aproveitar cada dia.', 'Map'),
    ('dicas-e-roteiros', 'Dicas Práticas', 'dicas-praticas', 'Informações para planejar melhor o passeio.', 'Info'),
    ('dicas-e-roteiros', 'Achados Locais', 'achados-locais', 'Lugares e programas que só quem é daqui conhece.', 'Gem')
) AS v(group_slug, name, slug, description, icon)
JOIN public.categories_group g ON g.slug = v.group_slug
JOIN LATERAL (
    SELECT uid FROM auth.users WHERE is_root = true ORDER BY created_at ASC LIMIT 1
) AS u(uid) ON true
JOIN LATERAL (
    SELECT tn.uid FROM auth.tenants tn WHERE tn.owner_uid = u.uid ORDER BY tn.created_at ASC LIMIT 1
) AS t(uid) ON true
ON CONFLICT (slug) DO UPDATE SET
  category_group_id = EXCLUDED.category_group_id, name = EXCLUDED.name,
  description = EXCLUDED.description, icon = EXCLUDED.icon, updated_at = now();

-- 3) Subcategorias (tags = palavras-chave de busca, cópia das tags da subcategoria) ------------
INSERT INTO public.categories_sub (category_id, name, slug, description, tags, active, tenant_id, created_by)
SELECT c.id, v.name, v.slug, v.description, v.tags, true, t.uid, u.uid
FROM (VALUES
    ('shows-e-musica-ao-vivo', 'Shows nacionais', 'shows-nacionais', 'Grandes turnês e artistas de fora passando pela cidade.', 'sertanejo, pop, rock, mpb, funk, pagode'),
    ('shows-e-musica-ao-vivo', 'Música regional', 'musica-regional', 'Ritmos mato-grossenses e da cultura pantaneira.', 'rasqueado, lambadão, siriri, cururu, viola de cocho'),
    ('shows-e-musica-ao-vivo', 'Eletrônica & raves', 'eletronica-e-raves', 'Festas de música eletrônica, open airs e DJ sets.', 'house, techno, open air, dj set, psytrance'),
    ('shows-e-musica-ao-vivo', 'Jazz, blues & instrumental', 'jazz-blues-e-instrumental', 'Noites intimistas de jazz, blues, choro e música instrumental.', 'jazz, blues, choro, orquestra, instrumental'),
    ('shows-e-musica-ao-vivo', 'Samba & pagode', 'samba-e-pagode', 'Rodas de samba e pagode para cantar junto.', 'roda de samba, pagode, samba de raiz, feijoada'),
    ('festas-e-baladas', 'Baladas', 'baladas', 'Noites em casas de show com pista, DJ e camarote.', 'open bar, camarote, lista vip, aniversário'),
    ('festas-e-baladas', 'Festas temáticas', 'festas-tematicas', 'Festas com tema, fantasia e trilha sonora especial.', 'anos 80 e 90, fantasia, pool party, festa sertaneja'),
    ('festas-e-baladas', 'Festas universitárias', 'festas-universitarias', 'Calouradas e festas organizadas por atléticas e repúblicas.', 'calourada, atlética, open bar, interclasse'),
    ('festas-e-baladas', 'Carnaval & Réveillon', 'carnaval-e-reveillon', 'Blocos de rua, bailes de carnaval e a virada do ano.', 'bloco de rua, abadá, baile de carnaval, queima de fogos, virada'),
    ('festas-tradicionais-e-religiosas', 'Festa de São Benedito', 'festa-de-sao-benedito', 'A festa religiosa mais tradicional de Cuiabá, com procissão e chá com bolo.', 'procissão, chá com bolo, cururu, festeiros, igreja do rosário'),
    ('festas-tradicionais-e-religiosas', 'Festas juninas & julinas', 'festas-juninas-e-julinas', 'Arraiás com quadrilha, fogueira e comidas típicas.', 'quadrilha, arraiá, quentão, fogueira, comidas típicas'),
    ('festas-tradicionais-e-religiosas', 'Festas de santo & romarias', 'festas-de-santo-e-romarias', 'Novenas, romarias e festas de padroeiros da região.', 'novena, romaria, padroeiro, missa campal'),
    ('festas-tradicionais-e-religiosas', 'Aniversário de Cuiabá', 'aniversario-de-cuiaba', 'Programação oficial de 8 de abril, com shows e atrações gratuitas.', '8 de abril, desfile, show gratuito, programação oficial'),
    ('festivais-e-exposicoes', 'Festivais de música', 'festivais-de-musica', 'Festivais com line-up, vários palcos e muita gente.', 'line-up, palco, ingresso, meia-entrada'),
    ('festivais-e-exposicoes', 'Festivais gastronômicos', 'festivais-gastronomicos', 'Eventos para comer bem: festivais de peixe, food trucks e cerveja.', 'festival do peixe, food truck, degustação, cerveja artesanal'),
    ('festivais-e-exposicoes', 'Exposições agropecuárias', 'exposicoes-agropecuarias', 'Expoagro, rodeios e leilões com shows sertanejos.', 'rodeio, leilão, parque de exposições, show sertanejo'),
    ('festivais-e-exposicoes', 'Feiras & convenções', 'feiras-e-convencoes', 'Convenções geek, feiras de tatuagem, anime e negócios.', 'geek, anime, tatuagem, negócios, cosplay'),
    ('palestras-e-encontros', 'Palestras & workshops', 'palestras-e-workshops', 'Conteúdo presencial com especialistas.', 'palestra, workshop, mão na massa, certificado'),
    ('palestras-e-encontros', 'Congressos & simpósios', 'congressos-e-simposios', 'Eventos acadêmicos e profissionais de maior porte.', 'congresso, simpósio, inscrição, credenciamento'),
    ('palestras-e-encontros', 'Meetups & networking', 'meetups-e-networking', 'Encontros de comunidades, tecnologia e empreendedorismo.', 'meetup, networking, startup, tecnologia'),
    ('cinema', 'Lançamentos', 'lancamentos', 'Estreias e filmes em cartaz na semana.', 'estreia, pré-estreia, 3d, legendado, dublado'),
    ('cinema', 'Cinema nacional & regional', 'cinema-nacional-e-regional', 'Produções brasileiras e mato-grossenses.', 'cinema brasileiro, documentário, produção mato-grossense, curta-metragem'),
    ('cinema', 'Mostras & cineclubes', 'mostras-e-cineclubes', 'Mostras temáticas, festivais de cinema e cineclubes.', 'mostra, cineclube, festival de cinema, debate'),
    ('cinema', 'Sessões especiais', 'sessoes-especiais', 'Sessões ao ar livre, maratonas e sessões infantis.', 'cinema ao ar livre, maratona, sessão infantil, sessão acessível'),
    ('teatro', 'Peças adultas', 'pecas-adultas', 'Dramas, comédias e montagens para o público adulto.', 'drama, comédia, monólogo, musical'),
    ('teatro', 'Teatro infantil', 'teatro-infantil', 'Peças e espetáculos pensados para crianças.', 'infantil, fantoches, contação de histórias, musical infantil'),
    ('teatro', 'Teatro de rua', 'teatro-de-rua', 'Apresentações gratuitas em praças e espaços públicos.', 'ao ar livre, gratuito, intervenção, praça'),
    ('humor-e-espetaculos', 'Stand-up & humor', 'stand-up-e-humor', 'Shows de comédia com humoristas locais e nacionais.', 'stand-up, improviso, humorista, open mic'),
    ('humor-e-espetaculos', 'Dança', 'danca', 'Balé, dança contemporânea e danças regionais no palco.', 'balé, contemporânea, dança regional, mostra de dança'),
    ('humor-e-espetaculos', 'Circo & mágica', 'circo-e-magica', 'Circos itinerantes, malabares e shows de mágica.', 'circo, palhaço, malabares, mágica'),
    ('trilhas', 'Trilhas leves', 'trilhas-leves', 'Percursos curtos e tranquilos, bons para iniciantes e famílias.', 'iniciante, família, até 5 km, sombra'),
    ('trilhas', 'Trilhas moderadas', 'trilhas-moderadas', 'Percursos com subidas e alguns trechos técnicos.', 'intermediário, 5 a 10 km, subida, bom preparo'),
    ('trilhas', 'Trilhas difíceis & travessias', 'trilhas-dificeis-e-travessias', 'Travessias longas, com desnível forte ou pernoite.', 'travessia, desnível, guia obrigatório, pernoite'),
    ('trilhas', 'Trilhas com cachoeira', 'trilhas-com-cachoeira', 'Caminhadas que terminam em queda d''água e poço para banho.', 'cachoeira, poço, banho, refrescante'),
    ('esportes-de-aventura', 'Rapel & escalada', 'rapel-e-escalada', 'Descidas em paredões e cachoeiras e escalada em rocha.', 'rapel, escalada, cascading, equipamento incluso'),
    ('esportes-de-aventura', 'Flutuação & boia-cross', 'flutuacao-e-boia-cross', 'Flutuação em águas cristalinas e descidas de boia em rios.', 'flutuação, boia-cross, snorkel, águas cristalinas'),
    ('esportes-de-aventura', 'Rafting', 'rafting', 'Descidas de bote em corredeiras, como em Jaciara.', 'rafting, corredeiras, jaciara, grupo'),
    ('esportes-de-aventura', 'Tirolesa & arvorismo', 'tirolesa-e-arvorismo', 'Circuitos suspensos e tirolesas sobre vales e rios.', 'tirolesa, arvorismo, altura, família'),
    ('esportes-de-aventura', 'Mountain bike', 'mountain-bike', 'Pedais em estradas de terra e trilhas de MTB.', 'mtb, gravel, estrada de terra, pedal de aventura'),
    ('mirantes-e-formacoes', 'Mirantes', 'mirantes', 'Lugares com vista ampla, ótimos para o pôr do sol.', 'pôr do sol, vista panorâmica, fotografia, nascer do sol'),
    ('mirantes-e-formacoes', 'Cavernas & grutas', 'cavernas-e-grutas', 'Cavernas e grutas como a Aroe Jari e a Lagoa Azul.', 'aroe jari, lagoa azul, espeleologia, lanterna'),
    ('mirantes-e-formacoes', 'Cidades de pedra & paredões', 'cidades-de-pedra-e-paredoes', 'Formações de arenito esculpidas pelo tempo.', 'cidade de pedra, arenito, paredão, geologia'),
    ('guias-e-agencias', 'Guias credenciados', 'guias-credenciados', 'Condutores locais cadastrados para trilhas e atrativos.', 'guia local, credenciado, condutor, segurança'),
    ('guias-e-agencias', 'Passeios guiados', 'passeios-guiados', 'Pacotes com roteiro, transporte e guia.', 'pacote, roteiro, saída diária, grupo pequeno'),
    ('guias-e-agencias', 'Transfer & 4x4', 'transfer-e-4x4', 'Transporte até atrativos de acesso difícil.', 'transfer, 4x4, aeroporto, estrada de terra'),
    ('guias-e-agencias', 'Aluguel de equipamentos', 'aluguel-de-equipamentos', 'Barracas, mochilas, bikes e equipamentos de aventura.', 'aluguel, barraca, bike, colete'),
    ('camping', 'Camping estruturado', 'camping-estruturado', 'Áreas com banheiro, energia e churrasqueira.', 'banheiro, energia, churrasqueira, área de barraca'),
    ('camping', 'Camping selvagem', 'camping-selvagem', 'Acampamento em áreas sem estrutura, com mínimo impacto.', 'sem estrutura, mínimo impacto, lanterna, autossuficiente'),
    ('camping', 'Glamping', 'glamping', 'Cabanas, domos e tendas equipadas no meio da natureza.', 'cabana, domo, conforto, romântico'),
    ('camping', 'Motorhome & overland', 'motorhome-e-overland', 'Pontos de apoio para motorhome, trailer e viagem de carro.', 'motorhome, trailer, ponto de apoio, overland'),
    ('cachoeiras-e-rios', 'Cachoeiras', 'cachoeiras', 'Quedas d''água com poço para banho na região.', 'queda d''água, poço natural, entrada paga, acesso fácil'),
    ('cachoeiras-e-rios', 'Balneários', 'balnearios', 'Balneários e day use à beira de rios.', 'balneário, day use, rio, quiosque'),
    ('cachoeiras-e-rios', 'Praias de rio', 'praias-de-rio', 'Prainhas que surgem na seca, como no Rio Cuiabá.', 'rio cuiabá, areia, temporada de seca, pesca'),
    ('cachoeiras-e-rios', 'Lagoas & nascentes', 'lagoas-e-nascentes', 'Nascentes e lagoas de água azul e transparente.', 'nascente, água azul, nobres, preservação'),
    ('pantanal-e-vida-selvagem', 'Safári fotográfico', 'safari-fotografico', 'Saídas para ver onças, jacarés e capivaras.', 'onça-pintada, porto jofre, focagem noturna, fotografia de natureza'),
    ('pantanal-e-vida-selvagem', 'Observação de aves', 'observacao-de-aves', 'Birdwatching com tuiuiús, araras-azuis e centenas de espécies.', 'birdwatching, tuiuiú, arara-azul, binóculo'),
    ('pantanal-e-vida-selvagem', 'Pesca esportiva', 'pesca-esportiva', 'Pesque e solte nos rios pantaneiros.', 'pesque e solte, pintado, pacu, dourado, piracema'),
    ('pantanal-e-vida-selvagem', 'Passeios de barco', 'passeios-de-barco', 'Chalanas, barcos-hotel e passeios ao pôr do sol no rio.', 'chalana, barco-hotel, pôr do sol no rio, voadeira'),
    ('parques-e-areas-verdes', 'Parques urbanos', 'parques-urbanos', 'Parques da cidade para caminhar, correr e relaxar.', 'mãe bonifácia, massairo okamura, zé bolo flô, caminhada'),
    ('parques-e-areas-verdes', 'Parques nacionais & estaduais', 'parques-nacionais-e-estaduais', 'Unidades de conservação com regras e horários próprios.', 'parque nacional, ingresso, horário de visita, regras'),
    ('parques-e-areas-verdes', 'Piqueniques', 'piqueniques', 'Lugares com sombra e gramado para um piquenique.', 'piquenique, sombra, gramado, pet friendly'),
    ('bares', 'Botecos & bares tradicionais', 'botecos-e-bares-tradicionais', 'Cerveja gelada, petisco e mesa na calçada.', 'boteco raiz, cerveja gelada, petisco, mesa na calçada'),
    ('bares', 'Bares com música ao vivo', 'bares-com-musica-ao-vivo', 'Bares com voz e violão, samba, sertanejo e rock.', 'voz e violão, banda, couvert artístico, sertanejo universitário'),
    ('bares', 'Choperias & cervejarias artesanais', 'choperias-e-cervejarias-artesanais', 'Chope, cerveja artesanal e torneiras rotativas.', 'chope, ipa, cervejaria artesanal, growler'),
    ('bares', 'Rooftops & bares com vista', 'rooftops-e-bares-com-vista', 'Bares no alto, com vista da cidade e pôr do sol.', 'vista, pôr do sol, drinks autorais, terraço'),
    ('bares', 'Bares esportivos', 'bares-esportivos', 'Telão, jogo ao vivo e torcida reunida.', 'telão, futebol, jogo ao vivo, torcida'),
    ('drinks-e-destilados', 'Bares de drinks', 'bares-de-drinks', 'Mixologia, drinks autorais e gin.', 'mixologia, drink autoral, gin, happy hour'),
    ('drinks-e-destilados', 'Adegas & vinhos', 'adegas-e-vinhos', 'Vinhos por taça, degustações e harmonizações.', 'vinho, degustação, harmonização, taça'),
    ('drinks-e-destilados', 'Cachaçarias & licores', 'cachacarias-e-licores', 'Cachaças artesanais e licores regionais, como o de pequi.', 'cachaça, licor de pequi, alambique, dose'),
    ('baladas-e-casas-noturnas', 'Casas noturnas', 'casas-noturnas', 'Casas com pista, DJ e programação semanal.', 'pista, dj, dress code, camarote'),
    ('baladas-e-casas-noturnas', 'Sertanejo & forró', 'sertanejo-e-forro', 'Noites para dançar a dois.', 'sertanejo, forró, arrocha, dança a dois'),
    ('baladas-e-casas-noturnas', 'Karaokê', 'karaoke', 'Para soltar a voz com os amigos.', 'karaokê, videokê, sala privativa, grupo'),
    ('baladas-e-casas-noturnas', 'LGBTQIA+', 'lgbtqia', 'Espaços e festas inclusivas, com drag shows e muita diversidade.', 'drag show, pride, inclusivo, diversidade'),
    ('happy-hour-e-petiscos', 'Happy hour', 'happy-hour', 'Promoções de bebida no fim do expediente.', 'promoção, dose dupla, fim de expediente, chope em dobro'),
    ('happy-hour-e-petiscos', 'Porções & petiscos', 'porcoes-e-petiscos', 'Isca de peixe, mandioca, torresmo e outras porções para dividir.', 'isca de peixe, mandioca frita, torresmo, para dividir'),
    ('happy-hour-e-petiscos', 'Espetinhos & conveniências', 'espetinhos-e-conveniencias', 'Espetinho na brasa e conveniências com mesinha na rua.', 'espetinho, conveniência, brasa, barato'),
    ('culinaria-cuiabana-e-pantaneira', 'Peixes de rio', 'peixes-de-rio', 'Pacu, pintado e piraputanga preparados do jeito cuiabano.', 'pacu assado, ventrecha de pacu, mojica de pintado, piraputanga, caldo de piranha'),
    ('culinaria-cuiabana-e-pantaneira', 'Pratos típicos', 'pratos-tipicos', 'Maria Isabel, farofa de banana, arroz com pequi e carne seca.', 'maria isabel, farofa de banana, arroz com pequi, carne seca, paçoca de pilão'),
    ('culinaria-cuiabana-e-pantaneira', 'Doces & quitutes', 'doces-e-quitutes', 'Bolo de arroz, furrundu, doce de caju e o tradicional chá com bolo.', 'bolo de arroz, furrundu, doce de caju, chá com bolo, francisquito'),
    ('culinaria-cuiabana-e-pantaneira', 'Comida de feira', 'comida-de-feira', 'Pastel, garapa e petiscos das feiras e mercados.', 'feira do porto, pastel, garapa, mercado'),
    ('restaurantes', 'Churrascarias', 'churrascarias', 'Rodízio, costela no fogo de chão e cortes nobres.', 'rodízio, costela, picanha, fogo de chão'),
    ('restaurantes', 'Cozinha contemporânea', 'cozinha-contemporanea', 'Restaurantes autorais, menu degustação e cozinha de chef.', 'autoral, menu degustação, chef, jantar especial'),
    ('restaurantes', 'Cozinha internacional', 'cozinha-internacional', 'Japonesa, italiana, árabe, mexicana e muito mais.', 'japonesa, italiana, árabe, mexicana, peruana'),
    ('restaurantes', 'Self-service & prato feito', 'self-service-e-prato-feito', 'Almoço rápido, por quilo, executivo ou PF.', 'por quilo, almoço executivo, prato feito, marmita'),
    ('restaurantes', 'Vegetariano & vegano', 'vegetariano-e-vegano', 'Opções sem carne e cardápios 100% vegetais.', 'vegetariano, vegano, plant-based, sem glúten'),
    ('cafes-e-docerias', 'Cafeterias', 'cafeterias', 'Café especial, brunch e espaço para trabalhar.', 'café especial, espresso, brunch, home office'),
    ('cafes-e-docerias', 'Padarias & confeitarias', 'padarias-e-confeitarias', 'Pão de queijo, bolos, doces finos e café da manhã.', 'pão de queijo, bolo, doces finos, café da manhã'),
    ('cafes-e-docerias', 'Sorveterias & açaí', 'sorveterias-e-acai', 'Sorvetes, picolés e açaí com frutas do cerrado.', 'sorvete, açaí, picolé, frutas do cerrado'),
    ('lanches-e-delivery', 'Hamburguerias', 'hamburguerias', 'Hambúrguer artesanal, smash e combos.', 'artesanal, smash, combo, batata frita'),
    ('lanches-e-delivery', 'Pizzarias', 'pizzarias', 'Rodízio, forno a lenha e pizza em casa.', 'rodízio de pizza, forno a lenha, borda recheada, delivery'),
    ('lanches-e-delivery', 'Food trucks & comida de rua', 'food-trucks-e-comida-de-rua', 'Food parks, cachorro-quente, tapioca e pastel.', 'food park, cachorro-quente, tapioca, comida de rua'),
    ('lanches-e-delivery', 'Delivery & madrugada', 'delivery-e-madrugada', 'Quem entrega rápido e quem atende de madrugada.', 'entrega grátis, aplicativo, madrugada, 24 horas'),
    ('cuiaba', 'Centro histórico', 'centro-historico', 'Igrejas, casarões e praças que contam a história de Cuiabá.', 'igreja do rosário e são benedito, casarões, praça da república, catedral'),
    ('cuiaba', 'Museus', 'museus', 'Museus de história, arte sacra, ciência e cultura regional.', 'museu do rio, arte sacra, história, exposição permanente'),
    ('cuiaba', 'Orla & Rio Cuiabá', 'orla-e-rio-cuiaba', 'O rio que batizou a cidade, com orla, calçadão e pôr do sol.', 'orla do porto, pôr do sol, aquário municipal, calçadão'),
    ('cuiaba', 'Marcos & mirantes urbanos', 'marcos-e-mirantes-urbanos', 'Obelisco do Centro Geodésico, Morro da Luz e vistas da cidade.', 'centro geodésico, obelisco, morro da luz, vista da cidade'),
    ('chapada-dos-guimaraes', 'Cachoeiras da Chapada', 'cachoeiras-da-chapada', 'Véu de Noiva e o circuito de cachoeiras do parque.', 'véu de noiva, circuito das cachoeiras, banho, parque nacional'),
    ('chapada-dos-guimaraes', 'Mirantes da Chapada', 'mirantes-da-chapada', 'Mirante do Centro Geodésico, Portão do Inferno e Morro de São Jerônimo.', 'mirante do centro geodésico, portão do inferno, morro de são jerônimo, pôr do sol'),
    ('chapada-dos-guimaraes', 'Vila da Chapada', 'vila-da-chapada', 'Praça, igreja, artesanato e restaurantes da cidade.', 'praça central, igreja de santana, artesanato, gastronomia'),
    ('chapada-dos-guimaraes', 'Parque Nacional da Chapada', 'parque-nacional-da-chapada', 'Horários, ingressos e regras do Parque Nacional.', 'ingresso, horários, trilhas guiadas, centro de visitantes'),
    ('pantanal', 'Transpantaneira', 'transpantaneira', 'A estrada-parque com mais de cem pontes de madeira até Porto Jofre.', 'poconé, pontes de madeira, porto jofre, estrada-parque'),
    ('pantanal', 'Barão de Melgaço', 'barao-de-melgaco', 'Baías, passeios de barco e a vida ribeirinha.', 'baías, ribeirinhos, passeio de barco, pesca'),
    ('pantanal', 'Fazendas & pousadas pantaneiras', 'fazendas-e-pousadas-pantaneiras', 'Hospedagem em fazendas com passeios inclusos.', 'fazenda, all inclusive, cavalgada, comitiva'),
    ('pantanal', 'Quando ir ao Pantanal', 'quando-ir-ao-pantanal', 'Cheia, seca e piracema: o que muda em cada época.', 'época de seca, época de cheia, piracema, calendário'),
    ('nobres-e-arredores', 'Nobres', 'nobres', 'Aquário Encantado, Bom Jardim e Lagoa das Araras.', 'aquário encantado, bom jardim, lagoa das araras, flutuação'),
    ('nobres-e-arredores', 'Jaciara', 'jaciara', 'Corredeiras, cachoeiras e rafting no Rio Tenente Amaral.', 'rafting, cachoeira da fumaça, rio tenente amaral, aventura'),
    ('nobres-e-arredores', 'Cáceres', 'caceres', 'Cidade histórica às margens do Rio Paraguai, famosa pela pesca.', 'rio paraguai, festival de pesca, centro histórico, pantanal norte'),
    ('nobres-e-arredores', 'Santo Antônio de Leverger', 'santo-antonio-de-leverger', 'Praias de rio e casas de pesca pertinho da capital.', 'praia de rio, rio cuiabá, casa de pesca, bate-volta'),
    ('nobres-e-arredores', 'Várzea Grande', 'varzea-grande', 'A cidade vizinha, com gastronomia, feiras e lazer.', 'gastronomia, feiras, aeroporto, lazer'),
    ('passeios-e-roteiros', 'City tour', 'city-tour', 'Passeios guiados pelos principais pontos da capital.', 'city tour, guia, ônibus turístico, histórico'),
    ('passeios-e-roteiros', 'Bate-volta', 'bate-volta', 'Passeios de um dia saindo de Cuiabá.', 'um dia, saída cedo, transporte incluso, almoço incluso'),
    ('passeios-e-roteiros', 'Turismo rural', 'turismo-rural', 'Fazendas, café colonial e cavalgadas.', 'fazenda, café colonial, cavalgada, ordenha'),
    ('cidade', 'Notícias de Cuiabá', 'noticias-de-cuiaba', 'O dia a dia da capital.', 'prefeitura, bairros, serviços, comunidade'),
    ('cidade', 'Notícias de Várzea Grande', 'noticias-de-varzea-grande', 'O dia a dia da cidade vizinha.', 'prefeitura, bairros, serviços, comunidade'),
    ('cidade', 'Trânsito & obras', 'transito-e-obras', 'Interdições, desvios e obras que afetam o seu caminho.', 'interdição, desvio, obras, transporte público'),
    ('cidade', 'Feriados & funcionamento', 'feriados-e-funcionamento', 'O que abre e fecha em feriados e datas especiais.', 'feriado, horário de funcionamento, ponto facultativo, comércio'),
    ('cultura-e-entretenimento', 'Novidades & inaugurações', 'novidades-e-inauguracoes', 'Novos bares, restaurantes e espaços abrindo as portas.', 'inauguração, novo espaço, reabertura, primeira visita'),
    ('cultura-e-entretenimento', 'Agenda da semana', 'agenda-da-semana', 'Resumo do que não dá para perder nos próximos dias.', 'agenda, destaques, fim de semana, imperdível'),
    ('cultura-e-entretenimento', 'Entrevistas & bastidores', 'entrevistas-e-bastidores', 'Conversas com artistas, chefs e produtores locais.', 'entrevista, bastidores, artista local, chef'),
    ('cultura-e-entretenimento', 'Rankings & listas', 'rankings-e-listas', 'Os melhores lugares, eleitos pelo público e pela redação.', 'ranking, top 10, melhores, votação'),
    ('meio-ambiente-e-clima', 'Clima & tempo', 'clima-e-tempo', 'Calor, frentes frias, chuva e umidade baixa.', 'calor, frente fria, chuva, umidade baixa'),
    ('meio-ambiente-e-clima', 'Queimadas & qualidade do ar', 'queimadas-e-qualidade-do-ar', 'Alertas de fumaça e focos de calor.', 'fumaça, qualidade do ar, focos de calor, alerta'),
    ('meio-ambiente-e-clima', 'Parques & acesso', 'parques-e-acesso', 'Fechamentos, reaberturas e novas regras nos parques.', 'fechamento, reabertura, regras, manutenção'),
    ('meio-ambiente-e-clima', 'Piracema & pesca', 'piracema-e-pesca', 'Períodos de proibição e fiscalização da pesca.', 'proibição, período de defeso, fiscalização, pesca liberada'),
    ('esportes', 'Futebol mato-grossense', 'futebol-mato-grossense', 'Cuiabá, Mixto, Dom Bosco e o campeonato estadual.', 'cuiabá ec, mixto, dom bosco, arena pantanal, mato-grossense'),
    ('esportes', 'Corridas & maratonas', 'corridas-e-maratonas', 'Resultados, calendário e inscrições de corridas.', 'calendário, resultado, inscrição, percurso'),
    ('esportes', 'Outros esportes', 'outros-esportes', 'Vôlei, basquete, lutas e esportes radicais.', 'vôlei, basquete, lutas, radicais'),
    ('exposicoes-e-galerias', 'Exposições', 'exposicoes', 'Mostras temporárias de arte e fotografia.', 'vernissage, mostra temporária, curadoria, entrada gratuita'),
    ('exposicoes-e-galerias', 'Galerias', 'galerias', 'Galerias de arte da cidade.', 'galeria, arte contemporânea, artista local, venda de obras'),
    ('exposicoes-e-galerias', 'Arte urbana', 'arte-urbana', 'Grafites, murais e intervenções pela cidade.', 'grafite, mural, lambe-lambe, intervenção urbana'),
    ('exposicoes-e-galerias', 'Fotografia', 'fotografia', 'Exposições, saídas fotográficas e fotoclubes.', 'saída fotográfica, fotoclube, exposição fotográfica, fotografia de rua'),
    ('cultura-popular-e-artesanato', 'Viola de cocho', 'viola-de-cocho', 'Instrumento patrimônio cultural, feito de um tronco só.', 'patrimônio, luthier, cururu, oficina'),
    ('cultura-popular-e-artesanato', 'Siriri & cururu', 'siriri-e-cururu', 'Danças e cantorias tradicionais e seus grupos folclóricos.', 'grupo folclórico, apresentação, dança típica, festival de siriri'),
    ('cultura-popular-e-artesanato', 'Cerâmica & artesanato', 'ceramica-e-artesanato', 'Cerâmica de São Gonçalo Beira Rio, bordados e cestaria.', 'são gonçalo beira rio, cerâmica, bordado, cestaria'),
    ('cultura-popular-e-artesanato', 'Cultura indígena', 'cultura-indigena', 'Arte, grafismo e saberes dos povos indígenas de Mato Grosso.', 'artesanato indígena, grafismo, bororo, saberes tradicionais'),
    ('espacos-culturais', 'Centros culturais', 'centros-culturais', 'Espaços com programação de teatro, música, cinema e oficinas.', 'programação, oficina, sesc arsenal, gratuito'),
    ('espacos-culturais', 'Bibliotecas & livrarias', 'bibliotecas-e-livrarias', 'Lugares para ler, estudar e ir a lançamentos.', 'leitura, lançamento de livro, clube do livro, estudo'),
    ('espacos-culturais', 'Saraus & poesia', 'saraus-e-poesia', 'Slams, saraus e microfone aberto.', 'slam, sarau, microfone aberto, poesia'),
    ('cursos-e-oficinas', 'Oficinas de arte', 'oficinas-de-arte', 'Pintura, desenho, cerâmica e artesanato.', 'pintura, desenho, cerâmica, iniciante'),
    ('cursos-e-oficinas', 'Música & instrumentos', 'musica-e-instrumentos', 'Aulas de violão, viola, canto e percussão.', 'violão, canto, percussão, aula experimental'),
    ('cursos-e-oficinas', 'Aulas de dança', 'aulas-de-danca', 'Forró, samba de gafieira, zouk, dança do ventre e mais.', 'forró, gafieira, zouk, dança de salão'),
    ('cursos-e-oficinas', 'Cursos de culinária', 'cursos-de-culinaria', 'Aprenda pratos cuiabanos, confeitaria e cozinha internacional.', 'culinária regional, confeitaria, churrasco, aula prática'),
    ('corrida-e-ciclismo', 'Corridas de rua', 'corridas-de-rua', 'Provas de 5K, 10K e meia maratona.', '5k, 10k, meia maratona, kit atleta'),
    ('corrida-e-ciclismo', 'Grupos de corrida', 'grupos-de-corrida', 'Assessorias e grupos que treinam juntos.', 'assessoria, treino coletivo, iniciantes, madrugada'),
    ('corrida-e-ciclismo', 'Pedal urbano', 'pedal-urbano', 'Pedais noturnos e passeios de bike pela cidade.', 'ciclovia, pedal noturno, grupo de pedal, bike compartilhada'),
    ('corrida-e-ciclismo', 'Ciclismo de estrada', 'ciclismo-de-estrada', 'Treinos e provas de speed nas rodovias da região.', 'speed, estrada, pelotão, prova'),
    ('esportes-aquaticos', 'Stand up paddle', 'stand-up-paddle', 'Remada em pé em rios e lagos.', 'sup, aula, aluguel de prancha, pôr do sol'),
    ('esportes-aquaticos', 'Caiaque & canoagem', 'caiaque-e-canoagem', 'Passeios e competições de caiaque.', 'caiaque, canoagem, remada, rio'),
    ('esportes-aquaticos', 'Natação em águas abertas', 'natacao-em-aguas-abertas', 'Travessias e treinos em rios e lagos.', 'águas abertas, travessia, treino, segurança'),
    ('esportes-aquaticos', 'Clubes & piscinas', 'clubes-e-piscinas', 'Clubes com piscina, day use e lazer para o calor.', 'clube, piscina, day use, sócio'),
    ('jogos-e-estadios', 'Futebol', 'futebol', 'Jogos no estádio, ingressos e peladas.', 'arena pantanal, ingresso, pelada, society'),
    ('jogos-e-estadios', 'Quadras & areia', 'quadras-e-areia', 'Vôlei, beach tennis, futevôlei e basquete.', 'beach tennis, futevôlei, vôlei de praia, basquete'),
    ('jogos-e-estadios', 'Lutas & MMA', 'lutas-e-mma', 'Eventos de luta, jiu-jitsu e academias.', 'mma, jiu-jitsu, boxe, muay thai'),
    ('jogos-e-estadios', 'Games & eSports', 'games-e-esports', 'Campeonatos, lan houses e bares de games.', 'esports, campeonato, fliperama, board games'),
    ('diversao-ao-ar-livre', 'Parques aquáticos', 'parques-aquaticos', 'Toboáguas e piscinas para refrescar.', 'toboágua, piscina de ondas, família, ingresso'),
    ('diversao-ao-ar-livre', 'Pesque-pague', 'pesque-pague', 'Pesca em tanques com peixe assado na hora.', 'tanque, pesca em família, peixe assado, aluguel de vara'),
    ('diversao-ao-ar-livre', 'Kart, paintball & boliche', 'kart-paintball-e-boliche', 'Diversão com adrenalina para a turma.', 'kart, paintball, boliche, laser tag'),
    ('passeios-em-familia', 'Parques & playgrounds', 'parques-e-playgrounds', 'Parques com brinquedos, sombra e espaço para correr.', 'playground, sombra, espaço aberto, gratuito'),
    ('passeios-em-familia', 'Zoológico & fauna', 'zoologico-e-fauna', 'Lugares para conhecer os animais do cerrado e do Pantanal.', 'zoológico, animais silvestres, educação ambiental, visita guiada'),
    ('passeios-em-familia', 'Fazendinhas', 'fazendinhas', 'Contato com animais, passeio a cavalo e vida no campo.', 'fazendinha, animais, passeio a cavalo, pomar'),
    ('passeios-em-familia', 'Ciência & descoberta', 'ciencia-e-descoberta', 'Museus interativos, planetário e experiências educativas.', 'interativo, planetário, experiências, educativo'),
    ('programacao-infantil', 'Contação de histórias', 'contacao-de-historias', 'Sessões de leitura e histórias encenadas.', 'contação, leitura, biblioteca, gratuito'),
    ('programacao-infantil', 'Oficinas infantis', 'oficinas-infantis', 'Arte, culinária e ciência para os pequenos.', 'oficina, arte, culinária kids, ciência'),
    ('programacao-infantil', 'Festas & buffets infantis', 'festas-e-buffets-infantis', 'Buffets e espaços para aniversários.', 'buffet, aniversário, recreação, decoração'),
    ('programacao-infantil', 'Colônia de férias', 'colonia-de-ferias', 'Programação especial nas férias escolares.', 'férias escolares, recreação, esportes, meio período'),
    ('restaurantes-para-criancas', 'Espaço kids', 'espaco-kids', 'Restaurantes com brinquedoteca e monitores.', 'brinquedoteca, monitor, parquinho, seguro'),
    ('restaurantes-para-criancas', 'Cardápio infantil', 'cardapio-infantil', 'Pratos e porções pensados para crianças.', 'menu kids, porção infantil, saudável, sobremesa'),
    ('feiras', 'Feiras livres', 'feiras-livres', 'Hortifrúti, pastel e garapa, com a Feira do Porto como símbolo.', 'hortifrúti, feira do porto, pastel, madrugada'),
    ('feiras', 'Feiras de artesanato', 'feiras-de-artesanato', 'Artesãos locais com peças únicas.', 'artesanato, feito à mão, artesão local, presentes'),
    ('feiras', 'Feiras orgânicas', 'feiras-organicas', 'Produtos orgânicos direto do produtor.', 'orgânico, agricultura familiar, direto do produtor, sem agrotóxico'),
    ('feiras', 'Brechós & feiras vintage', 'brechos-e-feiras-vintage', 'Moda circular, vinil e antiguidades.', 'brechó, vintage, vinil, antiguidades'),
    ('shoppings-e-lojas', 'Shoppings', 'shoppings', 'Lojas, praça de alimentação e cinema em um só lugar.', 'praça de alimentação, estacionamento, cinema, lojas'),
    ('shoppings-e-lojas', 'Lembranças & souvenirs', 'lembrancas-e-souvenirs', 'Presentes que lembram Mato Grosso.', 'souvenir, lembrancinha, viola de cocho em miniatura, camiseta'),
    ('shoppings-e-lojas', 'Empórios & produtos regionais', 'emporios-e-produtos-regionais', 'Pequi, doces, licores e cachaças da região.', 'pequi, doces caseiros, licor, cachaça'),
    ('moda-e-design-local', 'Marcas locais', 'marcas-locais', 'Moda e acessórios criados na região.', 'moda autoral, acessórios, estampa regional, sustentável'),
    ('moda-e-design-local', 'Ateliês', 'atelies', 'Estúdios de costura, joalheria e design.', 'sob medida, joalheria, costura, design'),
    ('moda-e-design-local', 'Bazares & pop-ups', 'bazares-e-pop-ups', 'Lojas temporárias e bazares de criadores.', 'pop-up, bazar, temporário, coletivo'),
    ('hoteis-e-pousadas', 'Hotéis em Cuiabá', 'hoteis-em-cuiaba', 'Hotéis na capital, perto do centro e do aeroporto.', 'centro, aeroporto, café da manhã, executivo'),
    ('hoteis-e-pousadas', 'Pousadas na Chapada', 'pousadas-na-chapada', 'Pousadas charmosas na vila e na serra.', 'vila, charme, lareira, vista da serra'),
    ('hoteis-e-pousadas', 'Pousadas no Pantanal', 'pousadas-no-pantanal', 'Pousadas à beira do rio e da Transpantaneira.', 'beira de rio, transpantaneira, pensão completa, passeios inclusos'),
    ('hoteis-e-pousadas', 'Resorts & hotéis-fazenda', 'resorts-e-hoteis-fazenda', 'Estrutura completa para desconectar.', 'resort, hotel-fazenda, piscina, recreação'),
    ('hospedagem-alternativa', 'Chalés & cabanas', 'chales-e-cabanas', 'Chalés na natureza, ótimos para casais.', 'chalé, cabana, hidromassagem, casal'),
    ('hospedagem-alternativa', 'Hostels', 'hostels', 'Hospedagem econômica e cheia de gente viajando.', 'quarto compartilhado, econômico, mochileiro, cozinha coletiva'),
    ('hospedagem-alternativa', 'Casas & chácaras de temporada', 'casas-e-chacaras-de-temporada', 'Casas inteiras para grupos e famílias.', 'casa inteira, chácara, piscina, grupo'),
    ('day-use', 'Day use em hotéis & resorts', 'day-use-em-hoteis-e-resorts', 'Piscina e estrutura de hotel por um dia.', 'piscina, almoço incluso, um dia, estrutura completa'),
    ('day-use', 'Day use em pousadas & chácaras', 'day-use-em-pousadas-e-chacaras', 'Dias de descanso em pousadas e chácaras perto da cidade.', 'chácara, pousada, natureza, perto de cuiabá'),
    ('spas-e-relaxamento', 'Spas & massagens', 'spas-e-massagens', 'Massagens relaxantes, terapêuticas e dias de spa.', 'massagem, day spa, pedras quentes, casal'),
    ('spas-e-relaxamento', 'Águas termais', 'aguas-termais', 'Banhos em águas quentes naturais da região.', 'águas termais, piscina natural, relaxamento, hotel'),
    ('yoga-e-meditacao', 'Yoga', 'yoga', 'Aulas em estúdios, parques e ao nascer do sol.', 'hatha, vinyasa, yoga no parque, aula experimental'),
    ('yoga-e-meditacao', 'Meditação', 'meditacao', 'Grupos e práticas guiadas.', 'meditação guiada, mindfulness, grupo, respiração'),
    ('yoga-e-meditacao', 'Retiros na natureza', 'retiros-na-natureza', 'Retiros de fim de semana na Chapada e no campo.', 'retiro, silêncio, chapada, detox digital'),
    ('atividade-fisica', 'Academias & estúdios', 'academias-e-estudios', 'Musculação, crossfit e estúdios especializados.', 'musculação, crossfit, estúdio, diária'),
    ('atividade-fisica', 'Treino funcional ao ar livre', 'treino-funcional-ao-ar-livre', 'Treinos em grupo nos parques da cidade.', 'funcional, parque, grupo, manhã cedo'),
    ('atividade-fisica', 'Pilates', 'pilates', 'Pilates de solo e em aparelhos.', 'pilates solo, aparelhos, postura, reabilitação'),
    ('roteiros-prontos', 'Um dia em Cuiabá', 'um-dia-em-cuiaba', 'O essencial da capital em um dia bem aproveitado.', 'manhã, almoço cuiabano, pôr do sol na orla, noite'),
    ('roteiros-prontos', 'Fim de semana na Chapada', 'fim-de-semana-na-chapada', 'Cachoeiras, mirantes e gastronomia em dois dias.', 'dois dias, cachoeiras, mirantes, onde comer'),
    ('roteiros-prontos', 'Três dias no Pantanal', 'tres-dias-no-pantanal', 'Transpantaneira, safári e passeio de barco.', 'três dias, safári, barco, pousada'),
    ('roteiros-prontos', 'Roteiro gastronômico', 'roteiro-gastronomico', 'Os sabores cuiabanos que você precisa provar.', 'peixe, doces típicos, chá com bolo, feira'),
    ('dicas-praticas', 'Melhor época para visitar', 'melhor-epoca-para-visitar', 'Seca, chuva e calor: o que esperar em cada mês.', 'seca, chuva, calor, alta temporada'),
    ('dicas-praticas', 'Como chegar & transporte', 'como-chegar-e-transporte', 'Aeroporto, ônibus, carro e aplicativos.', 'aeroporto, rodoviária, aluguel de carro, aplicativo'),
    ('dicas-praticas', 'Calor & segurança', 'calor-e-seguranca', 'Hidratação, protetor solar e cuidados nas trilhas.', 'hidratação, protetor solar, repelente, calor extremo'),
    ('dicas-praticas', 'Economize', 'economize', 'Programas gratuitos, meia-entrada e promoções.', 'gratuito, meia-entrada, promoção, cupom'),
    ('achados-locais', 'Lugares escondidos', 'lugares-escondidos', 'Cantinhos pouco conhecidos e sem aglomeração.', 'pouco conhecido, sem aglomeração, segredo local, tranquilo'),
    ('achados-locais', 'Programas baratos', 'programas-baratos', 'Diversão boa gastando pouco.', 'até r$ 50, gratuito, econômico, com amigos'),
    ('achados-locais', 'Programas românticos', 'programas-romanticos', 'Ideias para um encontro especial.', 'casal, pôr do sol, jantar, surpresa'),
    ('achados-locais', 'Pet friendly', 'pet-friendly', 'Lugares que recebem bem o seu pet.', 'pet friendly, cachorro, área pet, água para pet')
) AS v(category_slug, name, slug, description, tags)
JOIN public.categories c ON c.slug = v.category_slug
JOIN LATERAL (
    SELECT uid FROM auth.users WHERE is_root = true ORDER BY created_at ASC LIMIT 1
) AS u(uid) ON true
JOIN LATERAL (
    SELECT tn.uid FROM auth.tenants tn WHERE tn.owner_uid = u.uid ORDER BY tn.created_at ASC LIMIT 1
) AS t(uid) ON true
ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id, name = EXCLUDED.name,
  description = EXCLUDED.description, tags = EXCLUDED.tags, updated_at = now();

-- 4) Tags --------------------------------------------------------------------------------------
INSERT INTO public.categories_sub_tags (category_id, category_sub_id, name, slug, active, tenant_id, created_by)
SELECT s.category_id, s.id, v.name, v.slug, true, t.uid, u.uid
FROM (VALUES
    ('shows-nacionais', 'Sertanejo', 'sertanejo'),
    ('shows-nacionais', 'Pop', 'pop'),
    ('shows-nacionais', 'Rock', 'rock'),
    ('shows-nacionais', 'MPB', 'mpb'),
    ('shows-nacionais', 'Funk', 'funk'),
    ('shows-nacionais', 'Pagode', 'pagode'),
    ('musica-regional', 'Rasqueado', 'rasqueado'),
    ('musica-regional', 'Lambadão', 'lambadao'),
    ('musica-regional', 'Siriri', 'siriri'),
    ('musica-regional', 'Cururu', 'cururu'),
    ('musica-regional', 'Viola de cocho', 'viola-de-cocho'),
    ('eletronica-e-raves', 'House', 'house'),
    ('eletronica-e-raves', 'Techno', 'techno'),
    ('eletronica-e-raves', 'Open air', 'open-air'),
    ('eletronica-e-raves', 'DJ set', 'dj-set'),
    ('eletronica-e-raves', 'Psytrance', 'psytrance'),
    ('jazz-blues-e-instrumental', 'Jazz', 'jazz'),
    ('jazz-blues-e-instrumental', 'Blues', 'blues'),
    ('jazz-blues-e-instrumental', 'Choro', 'choro'),
    ('jazz-blues-e-instrumental', 'Orquestra', 'orquestra'),
    ('jazz-blues-e-instrumental', 'Instrumental', 'instrumental'),
    ('samba-e-pagode', 'Roda de samba', 'roda-de-samba'),
    ('samba-e-pagode', 'Pagode', 'pagode'),
    ('samba-e-pagode', 'Samba de raiz', 'samba-de-raiz'),
    ('samba-e-pagode', 'Feijoada', 'feijoada'),
    ('baladas', 'Open bar', 'open-bar'),
    ('baladas', 'Camarote', 'camarote'),
    ('baladas', 'Lista VIP', 'lista-vip'),
    ('baladas', 'Aniversário', 'aniversario'),
    ('festas-tematicas', 'Anos 80 e 90', 'anos-80-e-90'),
    ('festas-tematicas', 'Fantasia', 'fantasia'),
    ('festas-tematicas', 'Pool party', 'pool-party'),
    ('festas-tematicas', 'Festa sertaneja', 'festa-sertaneja'),
    ('festas-universitarias', 'Calourada', 'calourada'),
    ('festas-universitarias', 'Atlética', 'atletica'),
    ('festas-universitarias', 'Open bar', 'open-bar'),
    ('festas-universitarias', 'Interclasse', 'interclasse'),
    ('carnaval-e-reveillon', 'Bloco de rua', 'bloco-de-rua'),
    ('carnaval-e-reveillon', 'Abadá', 'abada'),
    ('carnaval-e-reveillon', 'Baile de carnaval', 'baile-de-carnaval'),
    ('carnaval-e-reveillon', 'Queima de fogos', 'queima-de-fogos'),
    ('carnaval-e-reveillon', 'Virada', 'virada'),
    ('festa-de-sao-benedito', 'Procissão', 'procissao'),
    ('festa-de-sao-benedito', 'Chá com bolo', 'cha-com-bolo'),
    ('festa-de-sao-benedito', 'Cururu', 'cururu'),
    ('festa-de-sao-benedito', 'Festeiros', 'festeiros'),
    ('festa-de-sao-benedito', 'Igreja do Rosário', 'igreja-do-rosario'),
    ('festas-juninas-e-julinas', 'Quadrilha', 'quadrilha'),
    ('festas-juninas-e-julinas', 'Arraiá', 'arraia'),
    ('festas-juninas-e-julinas', 'Quentão', 'quentao'),
    ('festas-juninas-e-julinas', 'Fogueira', 'fogueira'),
    ('festas-juninas-e-julinas', 'Comidas típicas', 'comidas-tipicas'),
    ('festas-de-santo-e-romarias', 'Novena', 'novena'),
    ('festas-de-santo-e-romarias', 'Romaria', 'romaria'),
    ('festas-de-santo-e-romarias', 'Padroeiro', 'padroeiro'),
    ('festas-de-santo-e-romarias', 'Missa campal', 'missa-campal'),
    ('aniversario-de-cuiaba', '8 de abril', '8-de-abril'),
    ('aniversario-de-cuiaba', 'Desfile', 'desfile'),
    ('aniversario-de-cuiaba', 'Show gratuito', 'show-gratuito'),
    ('aniversario-de-cuiaba', 'Programação oficial', 'programacao-oficial'),
    ('festivais-de-musica', 'Line-up', 'line-up'),
    ('festivais-de-musica', 'Palco', 'palco'),
    ('festivais-de-musica', 'Ingresso', 'ingresso'),
    ('festivais-de-musica', 'Meia-entrada', 'meia-entrada'),
    ('festivais-gastronomicos', 'Festival do peixe', 'festival-do-peixe'),
    ('festivais-gastronomicos', 'Food truck', 'food-truck'),
    ('festivais-gastronomicos', 'Degustação', 'degustacao'),
    ('festivais-gastronomicos', 'Cerveja artesanal', 'cerveja-artesanal'),
    ('exposicoes-agropecuarias', 'Rodeio', 'rodeio'),
    ('exposicoes-agropecuarias', 'Leilão', 'leilao'),
    ('exposicoes-agropecuarias', 'Parque de exposições', 'parque-de-exposicoes'),
    ('exposicoes-agropecuarias', 'Show sertanejo', 'show-sertanejo'),
    ('feiras-e-convencoes', 'Geek', 'geek'),
    ('feiras-e-convencoes', 'Anime', 'anime'),
    ('feiras-e-convencoes', 'Tatuagem', 'tatuagem'),
    ('feiras-e-convencoes', 'Negócios', 'negocios'),
    ('feiras-e-convencoes', 'Cosplay', 'cosplay'),
    ('palestras-e-workshops', 'Palestra', 'palestra'),
    ('palestras-e-workshops', 'Workshop', 'workshop'),
    ('palestras-e-workshops', 'Mão na massa', 'mao-na-massa'),
    ('palestras-e-workshops', 'Certificado', 'certificado'),
    ('congressos-e-simposios', 'Congresso', 'congresso'),
    ('congressos-e-simposios', 'Simpósio', 'simposio'),
    ('congressos-e-simposios', 'Inscrição', 'inscricao'),
    ('congressos-e-simposios', 'Credenciamento', 'credenciamento'),
    ('meetups-e-networking', 'Meetup', 'meetup'),
    ('meetups-e-networking', 'Networking', 'networking'),
    ('meetups-e-networking', 'Startup', 'startup'),
    ('meetups-e-networking', 'Tecnologia', 'tecnologia'),
    ('lancamentos', 'Estreia', 'estreia'),
    ('lancamentos', 'Pré-estreia', 'pre-estreia'),
    ('lancamentos', '3D', '3d'),
    ('lancamentos', 'Legendado', 'legendado'),
    ('lancamentos', 'Dublado', 'dublado'),
    ('cinema-nacional-e-regional', 'Cinema brasileiro', 'cinema-brasileiro'),
    ('cinema-nacional-e-regional', 'Documentário', 'documentario'),
    ('cinema-nacional-e-regional', 'Produção mato-grossense', 'producao-mato-grossense'),
    ('cinema-nacional-e-regional', 'Curta-metragem', 'curta-metragem'),
    ('mostras-e-cineclubes', 'Mostra', 'mostra'),
    ('mostras-e-cineclubes', 'Cineclube', 'cineclube'),
    ('mostras-e-cineclubes', 'Festival de cinema', 'festival-de-cinema'),
    ('mostras-e-cineclubes', 'Debate', 'debate'),
    ('sessoes-especiais', 'Cinema ao ar livre', 'cinema-ao-ar-livre'),
    ('sessoes-especiais', 'Maratona', 'maratona'),
    ('sessoes-especiais', 'Sessão infantil', 'sessao-infantil'),
    ('sessoes-especiais', 'Sessão acessível', 'sessao-acessivel'),
    ('pecas-adultas', 'Drama', 'drama'),
    ('pecas-adultas', 'Comédia', 'comedia'),
    ('pecas-adultas', 'Monólogo', 'monologo'),
    ('pecas-adultas', 'Musical', 'musical'),
    ('teatro-infantil', 'Infantil', 'infantil'),
    ('teatro-infantil', 'Fantoches', 'fantoches'),
    ('teatro-infantil', 'Contação de histórias', 'contacao-de-historias'),
    ('teatro-infantil', 'Musical infantil', 'musical-infantil'),
    ('teatro-de-rua', 'Ao ar livre', 'ao-ar-livre'),
    ('teatro-de-rua', 'Gratuito', 'gratuito'),
    ('teatro-de-rua', 'Intervenção', 'intervencao'),
    ('teatro-de-rua', 'Praça', 'praca'),
    ('stand-up-e-humor', 'Stand-up', 'stand-up'),
    ('stand-up-e-humor', 'Improviso', 'improviso'),
    ('stand-up-e-humor', 'Humorista', 'humorista'),
    ('stand-up-e-humor', 'Open mic', 'open-mic'),
    ('danca', 'Balé', 'bale'),
    ('danca', 'Contemporânea', 'contemporanea'),
    ('danca', 'Dança regional', 'danca-regional'),
    ('danca', 'Mostra de dança', 'mostra-de-danca'),
    ('circo-e-magica', 'Circo', 'circo'),
    ('circo-e-magica', 'Palhaço', 'palhaco'),
    ('circo-e-magica', 'Malabares', 'malabares'),
    ('circo-e-magica', 'Mágica', 'magica'),
    ('trilhas-leves', 'Iniciante', 'iniciante'),
    ('trilhas-leves', 'Família', 'familia'),
    ('trilhas-leves', 'Até 5 km', 'ate-5-km'),
    ('trilhas-leves', 'Sombra', 'sombra'),
    ('trilhas-moderadas', 'Intermediário', 'intermediario'),
    ('trilhas-moderadas', '5 a 10 km', '5-a-10-km'),
    ('trilhas-moderadas', 'Subida', 'subida'),
    ('trilhas-moderadas', 'Bom preparo', 'bom-preparo'),
    ('trilhas-dificeis-e-travessias', 'Travessia', 'travessia'),
    ('trilhas-dificeis-e-travessias', 'Desnível', 'desnivel'),
    ('trilhas-dificeis-e-travessias', 'Guia obrigatório', 'guia-obrigatorio'),
    ('trilhas-dificeis-e-travessias', 'Pernoite', 'pernoite'),
    ('trilhas-com-cachoeira', 'Cachoeira', 'cachoeira'),
    ('trilhas-com-cachoeira', 'Poço', 'poco'),
    ('trilhas-com-cachoeira', 'Banho', 'banho'),
    ('trilhas-com-cachoeira', 'Refrescante', 'refrescante'),
    ('rapel-e-escalada', 'Rapel', 'rapel'),
    ('rapel-e-escalada', 'Escalada', 'escalada'),
    ('rapel-e-escalada', 'Cascading', 'cascading'),
    ('rapel-e-escalada', 'Equipamento incluso', 'equipamento-incluso'),
    ('flutuacao-e-boia-cross', 'Flutuação', 'flutuacao'),
    ('flutuacao-e-boia-cross', 'Boia-cross', 'boia-cross'),
    ('flutuacao-e-boia-cross', 'Snorkel', 'snorkel'),
    ('flutuacao-e-boia-cross', 'Águas cristalinas', 'aguas-cristalinas'),
    ('rafting', 'Rafting', 'rafting'),
    ('rafting', 'Corredeiras', 'corredeiras'),
    ('rafting', 'Jaciara', 'jaciara'),
    ('rafting', 'Grupo', 'grupo'),
    ('tirolesa-e-arvorismo', 'Tirolesa', 'tirolesa'),
    ('tirolesa-e-arvorismo', 'Arvorismo', 'arvorismo'),
    ('tirolesa-e-arvorismo', 'Altura', 'altura'),
    ('tirolesa-e-arvorismo', 'Família', 'familia'),
    ('mountain-bike', 'MTB', 'mtb'),
    ('mountain-bike', 'Gravel', 'gravel'),
    ('mountain-bike', 'Estrada de terra', 'estrada-de-terra'),
    ('mountain-bike', 'Pedal de aventura', 'pedal-de-aventura'),
    ('mirantes', 'Pôr do sol', 'por-do-sol'),
    ('mirantes', 'Vista panorâmica', 'vista-panoramica'),
    ('mirantes', 'Fotografia', 'fotografia'),
    ('mirantes', 'Nascer do sol', 'nascer-do-sol'),
    ('cavernas-e-grutas', 'Aroe Jari', 'aroe-jari'),
    ('cavernas-e-grutas', 'Lagoa Azul', 'lagoa-azul'),
    ('cavernas-e-grutas', 'Espeleologia', 'espeleologia'),
    ('cavernas-e-grutas', 'Lanterna', 'lanterna'),
    ('cidades-de-pedra-e-paredoes', 'Cidade de Pedra', 'cidade-de-pedra'),
    ('cidades-de-pedra-e-paredoes', 'Arenito', 'arenito'),
    ('cidades-de-pedra-e-paredoes', 'Paredão', 'paredao'),
    ('cidades-de-pedra-e-paredoes', 'Geologia', 'geologia'),
    ('guias-credenciados', 'Guia local', 'guia-local'),
    ('guias-credenciados', 'Credenciado', 'credenciado'),
    ('guias-credenciados', 'Condutor', 'condutor'),
    ('guias-credenciados', 'Segurança', 'seguranca'),
    ('passeios-guiados', 'Pacote', 'pacote'),
    ('passeios-guiados', 'Roteiro', 'roteiro'),
    ('passeios-guiados', 'Saída diária', 'saida-diaria'),
    ('passeios-guiados', 'Grupo pequeno', 'grupo-pequeno'),
    ('transfer-e-4x4', 'Transfer', 'transfer'),
    ('transfer-e-4x4', '4x4', '4x4'),
    ('transfer-e-4x4', 'Aeroporto', 'aeroporto'),
    ('transfer-e-4x4', 'Estrada de terra', 'estrada-de-terra'),
    ('aluguel-de-equipamentos', 'Aluguel', 'aluguel'),
    ('aluguel-de-equipamentos', 'Barraca', 'barraca'),
    ('aluguel-de-equipamentos', 'Bike', 'bike'),
    ('aluguel-de-equipamentos', 'Colete', 'colete'),
    ('camping-estruturado', 'Banheiro', 'banheiro'),
    ('camping-estruturado', 'Energia', 'energia'),
    ('camping-estruturado', 'Churrasqueira', 'churrasqueira'),
    ('camping-estruturado', 'Área de barraca', 'area-de-barraca'),
    ('camping-selvagem', 'Sem estrutura', 'sem-estrutura'),
    ('camping-selvagem', 'Mínimo impacto', 'minimo-impacto'),
    ('camping-selvagem', 'Lanterna', 'lanterna'),
    ('camping-selvagem', 'Autossuficiente', 'autossuficiente'),
    ('glamping', 'Cabana', 'cabana'),
    ('glamping', 'Domo', 'domo'),
    ('glamping', 'Conforto', 'conforto'),
    ('glamping', 'Romântico', 'romantico'),
    ('motorhome-e-overland', 'Motorhome', 'motorhome'),
    ('motorhome-e-overland', 'Trailer', 'trailer'),
    ('motorhome-e-overland', 'Ponto de apoio', 'ponto-de-apoio'),
    ('motorhome-e-overland', 'Overland', 'overland'),
    ('cachoeiras', 'Queda d''água', 'queda-d-agua'),
    ('cachoeiras', 'Poço natural', 'poco-natural'),
    ('cachoeiras', 'Entrada paga', 'entrada-paga'),
    ('cachoeiras', 'Acesso fácil', 'acesso-facil'),
    ('balnearios', 'Balneário', 'balneario'),
    ('balnearios', 'Day use', 'day-use'),
    ('balnearios', 'Rio', 'rio'),
    ('balnearios', 'Quiosque', 'quiosque'),
    ('praias-de-rio', 'Rio Cuiabá', 'rio-cuiaba'),
    ('praias-de-rio', 'Areia', 'areia'),
    ('praias-de-rio', 'Temporada de seca', 'temporada-de-seca'),
    ('praias-de-rio', 'Pesca', 'pesca'),
    ('lagoas-e-nascentes', 'Nascente', 'nascente'),
    ('lagoas-e-nascentes', 'Água azul', 'agua-azul'),
    ('lagoas-e-nascentes', 'Nobres', 'nobres'),
    ('lagoas-e-nascentes', 'Preservação', 'preservacao'),
    ('safari-fotografico', 'Onça-pintada', 'onca-pintada'),
    ('safari-fotografico', 'Porto Jofre', 'porto-jofre'),
    ('safari-fotografico', 'Focagem noturna', 'focagem-noturna'),
    ('safari-fotografico', 'Fotografia de natureza', 'fotografia-de-natureza'),
    ('observacao-de-aves', 'Birdwatching', 'birdwatching'),
    ('observacao-de-aves', 'Tuiuiú', 'tuiuiu'),
    ('observacao-de-aves', 'Arara-azul', 'arara-azul'),
    ('observacao-de-aves', 'Binóculo', 'binoculo'),
    ('pesca-esportiva', 'Pesque e solte', 'pesque-e-solte'),
    ('pesca-esportiva', 'Pintado', 'pintado'),
    ('pesca-esportiva', 'Pacu', 'pacu'),
    ('pesca-esportiva', 'Dourado', 'dourado'),
    ('pesca-esportiva', 'Piracema', 'piracema'),
    ('passeios-de-barco', 'Chalana', 'chalana'),
    ('passeios-de-barco', 'Barco-hotel', 'barco-hotel'),
    ('passeios-de-barco', 'Pôr do sol no rio', 'por-do-sol-no-rio'),
    ('passeios-de-barco', 'Voadeira', 'voadeira'),
    ('parques-urbanos', 'Mãe Bonifácia', 'mae-bonifacia'),
    ('parques-urbanos', 'Massairo Okamura', 'massairo-okamura'),
    ('parques-urbanos', 'Zé Bolo Flô', 'ze-bolo-flo'),
    ('parques-urbanos', 'Caminhada', 'caminhada'),
    ('parques-nacionais-e-estaduais', 'Parque Nacional', 'parque-nacional'),
    ('parques-nacionais-e-estaduais', 'Ingresso', 'ingresso'),
    ('parques-nacionais-e-estaduais', 'Horário de visita', 'horario-de-visita'),
    ('parques-nacionais-e-estaduais', 'Regras', 'regras'),
    ('piqueniques', 'Piquenique', 'piquenique'),
    ('piqueniques', 'Sombra', 'sombra'),
    ('piqueniques', 'Gramado', 'gramado'),
    ('piqueniques', 'Pet friendly', 'pet-friendly'),
    ('botecos-e-bares-tradicionais', 'Boteco raiz', 'boteco-raiz'),
    ('botecos-e-bares-tradicionais', 'Cerveja gelada', 'cerveja-gelada'),
    ('botecos-e-bares-tradicionais', 'Petisco', 'petisco'),
    ('botecos-e-bares-tradicionais', 'Mesa na calçada', 'mesa-na-calcada'),
    ('bares-com-musica-ao-vivo', 'Voz e violão', 'voz-e-violao'),
    ('bares-com-musica-ao-vivo', 'Banda', 'banda'),
    ('bares-com-musica-ao-vivo', 'Couvert artístico', 'couvert-artistico'),
    ('bares-com-musica-ao-vivo', 'Sertanejo universitário', 'sertanejo-universitario'),
    ('choperias-e-cervejarias-artesanais', 'Chope', 'chope'),
    ('choperias-e-cervejarias-artesanais', 'IPA', 'ipa'),
    ('choperias-e-cervejarias-artesanais', 'Cervejaria artesanal', 'cervejaria-artesanal'),
    ('choperias-e-cervejarias-artesanais', 'Growler', 'growler'),
    ('rooftops-e-bares-com-vista', 'Vista', 'vista'),
    ('rooftops-e-bares-com-vista', 'Pôr do sol', 'por-do-sol'),
    ('rooftops-e-bares-com-vista', 'Drinks autorais', 'drinks-autorais'),
    ('rooftops-e-bares-com-vista', 'Terraço', 'terraco'),
    ('bares-esportivos', 'Telão', 'telao'),
    ('bares-esportivos', 'Futebol', 'futebol'),
    ('bares-esportivos', 'Jogo ao vivo', 'jogo-ao-vivo'),
    ('bares-esportivos', 'Torcida', 'torcida'),
    ('bares-de-drinks', 'Mixologia', 'mixologia'),
    ('bares-de-drinks', 'Drink autoral', 'drink-autoral'),
    ('bares-de-drinks', 'Gin', 'gin'),
    ('bares-de-drinks', 'Happy hour', 'happy-hour'),
    ('adegas-e-vinhos', 'Vinho', 'vinho'),
    ('adegas-e-vinhos', 'Degustação', 'degustacao'),
    ('adegas-e-vinhos', 'Harmonização', 'harmonizacao'),
    ('adegas-e-vinhos', 'Taça', 'taca'),
    ('cachacarias-e-licores', 'Cachaça', 'cachaca'),
    ('cachacarias-e-licores', 'Licor de pequi', 'licor-de-pequi'),
    ('cachacarias-e-licores', 'Alambique', 'alambique'),
    ('cachacarias-e-licores', 'Dose', 'dose'),
    ('casas-noturnas', 'Pista', 'pista'),
    ('casas-noturnas', 'DJ', 'dj'),
    ('casas-noturnas', 'Dress code', 'dress-code'),
    ('casas-noturnas', 'Camarote', 'camarote'),
    ('sertanejo-e-forro', 'Sertanejo', 'sertanejo'),
    ('sertanejo-e-forro', 'Forró', 'forro'),
    ('sertanejo-e-forro', 'Arrocha', 'arrocha'),
    ('sertanejo-e-forro', 'Dança a dois', 'danca-a-dois'),
    ('karaoke', 'Karaokê', 'karaoke'),
    ('karaoke', 'Videokê', 'videoke'),
    ('karaoke', 'Sala privativa', 'sala-privativa'),
    ('karaoke', 'Grupo', 'grupo'),
    ('lgbtqia', 'Drag show', 'drag-show'),
    ('lgbtqia', 'Pride', 'pride'),
    ('lgbtqia', 'Inclusivo', 'inclusivo'),
    ('lgbtqia', 'Diversidade', 'diversidade'),
    ('happy-hour', 'Promoção', 'promocao'),
    ('happy-hour', 'Dose dupla', 'dose-dupla'),
    ('happy-hour', 'Fim de expediente', 'fim-de-expediente'),
    ('happy-hour', 'Chope em dobro', 'chope-em-dobro'),
    ('porcoes-e-petiscos', 'Isca de peixe', 'isca-de-peixe'),
    ('porcoes-e-petiscos', 'Mandioca frita', 'mandioca-frita'),
    ('porcoes-e-petiscos', 'Torresmo', 'torresmo'),
    ('porcoes-e-petiscos', 'Para dividir', 'para-dividir'),
    ('espetinhos-e-conveniencias', 'Espetinho', 'espetinho'),
    ('espetinhos-e-conveniencias', 'Conveniência', 'conveniencia'),
    ('espetinhos-e-conveniencias', 'Brasa', 'brasa'),
    ('espetinhos-e-conveniencias', 'Barato', 'barato'),
    ('peixes-de-rio', 'Pacu assado', 'pacu-assado'),
    ('peixes-de-rio', 'Ventrecha de pacu', 'ventrecha-de-pacu'),
    ('peixes-de-rio', 'Mojica de pintado', 'mojica-de-pintado'),
    ('peixes-de-rio', 'Piraputanga', 'piraputanga'),
    ('peixes-de-rio', 'Caldo de piranha', 'caldo-de-piranha'),
    ('pratos-tipicos', 'Maria Isabel', 'maria-isabel'),
    ('pratos-tipicos', 'Farofa de banana', 'farofa-de-banana'),
    ('pratos-tipicos', 'Arroz com pequi', 'arroz-com-pequi'),
    ('pratos-tipicos', 'Carne seca', 'carne-seca'),
    ('pratos-tipicos', 'Paçoca de pilão', 'pacoca-de-pilao'),
    ('doces-e-quitutes', 'Bolo de arroz', 'bolo-de-arroz'),
    ('doces-e-quitutes', 'Furrundu', 'furrundu'),
    ('doces-e-quitutes', 'Doce de caju', 'doce-de-caju'),
    ('doces-e-quitutes', 'Chá com bolo', 'cha-com-bolo'),
    ('doces-e-quitutes', 'Francisquito', 'francisquito'),
    ('comida-de-feira', 'Feira do Porto', 'feira-do-porto'),
    ('comida-de-feira', 'Pastel', 'pastel'),
    ('comida-de-feira', 'Garapa', 'garapa'),
    ('comida-de-feira', 'Mercado', 'mercado'),
    ('churrascarias', 'Rodízio', 'rodizio'),
    ('churrascarias', 'Costela', 'costela'),
    ('churrascarias', 'Picanha', 'picanha'),
    ('churrascarias', 'Fogo de chão', 'fogo-de-chao'),
    ('cozinha-contemporanea', 'Autoral', 'autoral'),
    ('cozinha-contemporanea', 'Menu degustação', 'menu-degustacao'),
    ('cozinha-contemporanea', 'Chef', 'chef'),
    ('cozinha-contemporanea', 'Jantar especial', 'jantar-especial'),
    ('cozinha-internacional', 'Japonesa', 'japonesa'),
    ('cozinha-internacional', 'Italiana', 'italiana'),
    ('cozinha-internacional', 'Árabe', 'arabe'),
    ('cozinha-internacional', 'Mexicana', 'mexicana'),
    ('cozinha-internacional', 'Peruana', 'peruana'),
    ('self-service-e-prato-feito', 'Por quilo', 'por-quilo'),
    ('self-service-e-prato-feito', 'Almoço executivo', 'almoco-executivo'),
    ('self-service-e-prato-feito', 'Prato feito', 'prato-feito'),
    ('self-service-e-prato-feito', 'Marmita', 'marmita'),
    ('vegetariano-e-vegano', 'Vegetariano', 'vegetariano'),
    ('vegetariano-e-vegano', 'Vegano', 'vegano'),
    ('vegetariano-e-vegano', 'Plant-based', 'plant-based'),
    ('vegetariano-e-vegano', 'Sem glúten', 'sem-gluten'),
    ('cafeterias', 'Café especial', 'cafe-especial'),
    ('cafeterias', 'Espresso', 'espresso'),
    ('cafeterias', 'Brunch', 'brunch'),
    ('cafeterias', 'Home office', 'home-office'),
    ('padarias-e-confeitarias', 'Pão de queijo', 'pao-de-queijo'),
    ('padarias-e-confeitarias', 'Bolo', 'bolo'),
    ('padarias-e-confeitarias', 'Doces finos', 'doces-finos'),
    ('padarias-e-confeitarias', 'Café da manhã', 'cafe-da-manha'),
    ('sorveterias-e-acai', 'Sorvete', 'sorvete'),
    ('sorveterias-e-acai', 'Açaí', 'acai'),
    ('sorveterias-e-acai', 'Picolé', 'picole'),
    ('sorveterias-e-acai', 'Frutas do cerrado', 'frutas-do-cerrado'),
    ('hamburguerias', 'Artesanal', 'artesanal'),
    ('hamburguerias', 'Smash', 'smash'),
    ('hamburguerias', 'Combo', 'combo'),
    ('hamburguerias', 'Batata frita', 'batata-frita'),
    ('pizzarias', 'Rodízio de pizza', 'rodizio-de-pizza'),
    ('pizzarias', 'Forno a lenha', 'forno-a-lenha'),
    ('pizzarias', 'Borda recheada', 'borda-recheada'),
    ('pizzarias', 'Delivery', 'delivery'),
    ('food-trucks-e-comida-de-rua', 'Food park', 'food-park'),
    ('food-trucks-e-comida-de-rua', 'Cachorro-quente', 'cachorro-quente'),
    ('food-trucks-e-comida-de-rua', 'Tapioca', 'tapioca'),
    ('food-trucks-e-comida-de-rua', 'Comida de rua', 'comida-de-rua'),
    ('delivery-e-madrugada', 'Entrega grátis', 'entrega-gratis'),
    ('delivery-e-madrugada', 'Aplicativo', 'aplicativo'),
    ('delivery-e-madrugada', 'Madrugada', 'madrugada'),
    ('delivery-e-madrugada', '24 horas', '24-horas'),
    ('centro-historico', 'Igreja do Rosário e São Benedito', 'igreja-do-rosario-e-sao-benedito'),
    ('centro-historico', 'Casarões', 'casaroes'),
    ('centro-historico', 'Praça da República', 'praca-da-republica'),
    ('centro-historico', 'Catedral', 'catedral'),
    ('museus', 'Museu do Rio', 'museu-do-rio'),
    ('museus', 'Arte sacra', 'arte-sacra'),
    ('museus', 'História', 'historia'),
    ('museus', 'Exposição permanente', 'exposicao-permanente'),
    ('orla-e-rio-cuiaba', 'Orla do Porto', 'orla-do-porto'),
    ('orla-e-rio-cuiaba', 'Pôr do sol', 'por-do-sol'),
    ('orla-e-rio-cuiaba', 'Aquário Municipal', 'aquario-municipal'),
    ('orla-e-rio-cuiaba', 'Calçadão', 'calcadao'),
    ('marcos-e-mirantes-urbanos', 'Centro Geodésico', 'centro-geodesico'),
    ('marcos-e-mirantes-urbanos', 'Obelisco', 'obelisco'),
    ('marcos-e-mirantes-urbanos', 'Morro da Luz', 'morro-da-luz'),
    ('marcos-e-mirantes-urbanos', 'Vista da cidade', 'vista-da-cidade'),
    ('cachoeiras-da-chapada', 'Véu de Noiva', 'veu-de-noiva'),
    ('cachoeiras-da-chapada', 'Circuito das cachoeiras', 'circuito-das-cachoeiras'),
    ('cachoeiras-da-chapada', 'Banho', 'banho'),
    ('cachoeiras-da-chapada', 'Parque Nacional', 'parque-nacional'),
    ('mirantes-da-chapada', 'Mirante do Centro Geodésico', 'mirante-do-centro-geodesico'),
    ('mirantes-da-chapada', 'Portão do Inferno', 'portao-do-inferno'),
    ('mirantes-da-chapada', 'Morro de São Jerônimo', 'morro-de-sao-jeronimo'),
    ('mirantes-da-chapada', 'Pôr do sol', 'por-do-sol'),
    ('vila-da-chapada', 'Praça central', 'praca-central'),
    ('vila-da-chapada', 'Igreja de Santana', 'igreja-de-santana'),
    ('vila-da-chapada', 'Artesanato', 'artesanato'),
    ('vila-da-chapada', 'Gastronomia', 'gastronomia'),
    ('parque-nacional-da-chapada', 'Ingresso', 'ingresso'),
    ('parque-nacional-da-chapada', 'Horários', 'horarios'),
    ('parque-nacional-da-chapada', 'Trilhas guiadas', 'trilhas-guiadas'),
    ('parque-nacional-da-chapada', 'Centro de visitantes', 'centro-de-visitantes'),
    ('transpantaneira', 'Poconé', 'pocone'),
    ('transpantaneira', 'Pontes de madeira', 'pontes-de-madeira'),
    ('transpantaneira', 'Porto Jofre', 'porto-jofre'),
    ('transpantaneira', 'Estrada-parque', 'estrada-parque'),
    ('barao-de-melgaco', 'Baías', 'baias'),
    ('barao-de-melgaco', 'Ribeirinhos', 'ribeirinhos'),
    ('barao-de-melgaco', 'Passeio de barco', 'passeio-de-barco'),
    ('barao-de-melgaco', 'Pesca', 'pesca'),
    ('fazendas-e-pousadas-pantaneiras', 'Fazenda', 'fazenda'),
    ('fazendas-e-pousadas-pantaneiras', 'All inclusive', 'all-inclusive'),
    ('fazendas-e-pousadas-pantaneiras', 'Cavalgada', 'cavalgada'),
    ('fazendas-e-pousadas-pantaneiras', 'Comitiva', 'comitiva'),
    ('quando-ir-ao-pantanal', 'Época de seca', 'epoca-de-seca'),
    ('quando-ir-ao-pantanal', 'Época de cheia', 'epoca-de-cheia'),
    ('quando-ir-ao-pantanal', 'Piracema', 'piracema'),
    ('quando-ir-ao-pantanal', 'Calendário', 'calendario'),
    ('nobres', 'Aquário Encantado', 'aquario-encantado'),
    ('nobres', 'Bom Jardim', 'bom-jardim'),
    ('nobres', 'Lagoa das Araras', 'lagoa-das-araras'),
    ('nobres', 'Flutuação', 'flutuacao'),
    ('jaciara', 'Rafting', 'rafting'),
    ('jaciara', 'Cachoeira da Fumaça', 'cachoeira-da-fumaca'),
    ('jaciara', 'Rio Tenente Amaral', 'rio-tenente-amaral'),
    ('jaciara', 'Aventura', 'aventura'),
    ('caceres', 'Rio Paraguai', 'rio-paraguai'),
    ('caceres', 'Festival de pesca', 'festival-de-pesca'),
    ('caceres', 'Centro histórico', 'centro-historico'),
    ('caceres', 'Pantanal norte', 'pantanal-norte'),
    ('santo-antonio-de-leverger', 'Praia de rio', 'praia-de-rio'),
    ('santo-antonio-de-leverger', 'Rio Cuiabá', 'rio-cuiaba'),
    ('santo-antonio-de-leverger', 'Casa de pesca', 'casa-de-pesca'),
    ('santo-antonio-de-leverger', 'Bate-volta', 'bate-volta'),
    ('varzea-grande', 'Gastronomia', 'gastronomia'),
    ('varzea-grande', 'Feiras', 'feiras'),
    ('varzea-grande', 'Aeroporto', 'aeroporto'),
    ('varzea-grande', 'Lazer', 'lazer'),
    ('city-tour', 'City tour', 'city-tour'),
    ('city-tour', 'Guia', 'guia'),
    ('city-tour', 'Ônibus turístico', 'onibus-turistico'),
    ('city-tour', 'Histórico', 'historico'),
    ('bate-volta', 'Um dia', 'um-dia'),
    ('bate-volta', 'Saída cedo', 'saida-cedo'),
    ('bate-volta', 'Transporte incluso', 'transporte-incluso'),
    ('bate-volta', 'Almoço incluso', 'almoco-incluso'),
    ('turismo-rural', 'Fazenda', 'fazenda'),
    ('turismo-rural', 'Café colonial', 'cafe-colonial'),
    ('turismo-rural', 'Cavalgada', 'cavalgada'),
    ('turismo-rural', 'Ordenha', 'ordenha'),
    ('noticias-de-cuiaba', 'Prefeitura', 'prefeitura'),
    ('noticias-de-cuiaba', 'Bairros', 'bairros'),
    ('noticias-de-cuiaba', 'Serviços', 'servicos'),
    ('noticias-de-cuiaba', 'Comunidade', 'comunidade'),
    ('noticias-de-varzea-grande', 'Prefeitura', 'prefeitura'),
    ('noticias-de-varzea-grande', 'Bairros', 'bairros'),
    ('noticias-de-varzea-grande', 'Serviços', 'servicos'),
    ('noticias-de-varzea-grande', 'Comunidade', 'comunidade'),
    ('transito-e-obras', 'Interdição', 'interdicao'),
    ('transito-e-obras', 'Desvio', 'desvio'),
    ('transito-e-obras', 'Obras', 'obras'),
    ('transito-e-obras', 'Transporte público', 'transporte-publico'),
    ('feriados-e-funcionamento', 'Feriado', 'feriado'),
    ('feriados-e-funcionamento', 'Horário de funcionamento', 'horario-de-funcionamento'),
    ('feriados-e-funcionamento', 'Ponto facultativo', 'ponto-facultativo'),
    ('feriados-e-funcionamento', 'Comércio', 'comercio'),
    ('novidades-e-inauguracoes', 'Inauguração', 'inauguracao'),
    ('novidades-e-inauguracoes', 'Novo espaço', 'novo-espaco'),
    ('novidades-e-inauguracoes', 'Reabertura', 'reabertura'),
    ('novidades-e-inauguracoes', 'Primeira visita', 'primeira-visita'),
    ('agenda-da-semana', 'Agenda', 'agenda'),
    ('agenda-da-semana', 'Destaques', 'destaques'),
    ('agenda-da-semana', 'Fim de semana', 'fim-de-semana'),
    ('agenda-da-semana', 'Imperdível', 'imperdivel'),
    ('entrevistas-e-bastidores', 'Entrevista', 'entrevista'),
    ('entrevistas-e-bastidores', 'Bastidores', 'bastidores'),
    ('entrevistas-e-bastidores', 'Artista local', 'artista-local'),
    ('entrevistas-e-bastidores', 'Chef', 'chef'),
    ('rankings-e-listas', 'Ranking', 'ranking'),
    ('rankings-e-listas', 'Top 10', 'top-10'),
    ('rankings-e-listas', 'Melhores', 'melhores'),
    ('rankings-e-listas', 'Votação', 'votacao'),
    ('clima-e-tempo', 'Calor', 'calor'),
    ('clima-e-tempo', 'Frente fria', 'frente-fria'),
    ('clima-e-tempo', 'Chuva', 'chuva'),
    ('clima-e-tempo', 'Umidade baixa', 'umidade-baixa'),
    ('queimadas-e-qualidade-do-ar', 'Fumaça', 'fumaca'),
    ('queimadas-e-qualidade-do-ar', 'Qualidade do ar', 'qualidade-do-ar'),
    ('queimadas-e-qualidade-do-ar', 'Focos de calor', 'focos-de-calor'),
    ('queimadas-e-qualidade-do-ar', 'Alerta', 'alerta'),
    ('parques-e-acesso', 'Fechamento', 'fechamento'),
    ('parques-e-acesso', 'Reabertura', 'reabertura'),
    ('parques-e-acesso', 'Regras', 'regras'),
    ('parques-e-acesso', 'Manutenção', 'manutencao'),
    ('piracema-e-pesca', 'Proibição', 'proibicao'),
    ('piracema-e-pesca', 'Período de defeso', 'periodo-de-defeso'),
    ('piracema-e-pesca', 'Fiscalização', 'fiscalizacao'),
    ('piracema-e-pesca', 'Pesca liberada', 'pesca-liberada'),
    ('futebol-mato-grossense', 'Cuiabá EC', 'cuiaba-ec'),
    ('futebol-mato-grossense', 'Mixto', 'mixto'),
    ('futebol-mato-grossense', 'Dom Bosco', 'dom-bosco'),
    ('futebol-mato-grossense', 'Arena Pantanal', 'arena-pantanal'),
    ('futebol-mato-grossense', 'Mato-grossense', 'mato-grossense'),
    ('corridas-e-maratonas', 'Calendário', 'calendario'),
    ('corridas-e-maratonas', 'Resultado', 'resultado'),
    ('corridas-e-maratonas', 'Inscrição', 'inscricao'),
    ('corridas-e-maratonas', 'Percurso', 'percurso'),
    ('outros-esportes', 'Vôlei', 'volei'),
    ('outros-esportes', 'Basquete', 'basquete'),
    ('outros-esportes', 'Lutas', 'lutas'),
    ('outros-esportes', 'Radicais', 'radicais'),
    ('exposicoes', 'Vernissage', 'vernissage'),
    ('exposicoes', 'Mostra temporária', 'mostra-temporaria'),
    ('exposicoes', 'Curadoria', 'curadoria'),
    ('exposicoes', 'Entrada gratuita', 'entrada-gratuita'),
    ('galerias', 'Galeria', 'galeria'),
    ('galerias', 'Arte contemporânea', 'arte-contemporanea'),
    ('galerias', 'Artista local', 'artista-local'),
    ('galerias', 'Venda de obras', 'venda-de-obras'),
    ('arte-urbana', 'Grafite', 'grafite'),
    ('arte-urbana', 'Mural', 'mural'),
    ('arte-urbana', 'Lambe-lambe', 'lambe-lambe'),
    ('arte-urbana', 'Intervenção urbana', 'intervencao-urbana'),
    ('fotografia', 'Saída fotográfica', 'saida-fotografica'),
    ('fotografia', 'Fotoclube', 'fotoclube'),
    ('fotografia', 'Exposição fotográfica', 'exposicao-fotografica'),
    ('fotografia', 'Fotografia de rua', 'fotografia-de-rua'),
    ('viola-de-cocho', 'Patrimônio', 'patrimonio'),
    ('viola-de-cocho', 'Luthier', 'luthier'),
    ('viola-de-cocho', 'Cururu', 'cururu'),
    ('viola-de-cocho', 'Oficina', 'oficina'),
    ('siriri-e-cururu', 'Grupo folclórico', 'grupo-folclorico'),
    ('siriri-e-cururu', 'Apresentação', 'apresentacao'),
    ('siriri-e-cururu', 'Dança típica', 'danca-tipica'),
    ('siriri-e-cururu', 'Festival de siriri', 'festival-de-siriri'),
    ('ceramica-e-artesanato', 'São Gonçalo Beira Rio', 'sao-goncalo-beira-rio'),
    ('ceramica-e-artesanato', 'Cerâmica', 'ceramica'),
    ('ceramica-e-artesanato', 'Bordado', 'bordado'),
    ('ceramica-e-artesanato', 'Cestaria', 'cestaria'),
    ('cultura-indigena', 'Artesanato indígena', 'artesanato-indigena'),
    ('cultura-indigena', 'Grafismo', 'grafismo'),
    ('cultura-indigena', 'Bororo', 'bororo'),
    ('cultura-indigena', 'Saberes tradicionais', 'saberes-tradicionais'),
    ('centros-culturais', 'Programação', 'programacao'),
    ('centros-culturais', 'Oficina', 'oficina'),
    ('centros-culturais', 'Sesc Arsenal', 'sesc-arsenal'),
    ('centros-culturais', 'Gratuito', 'gratuito'),
    ('bibliotecas-e-livrarias', 'Leitura', 'leitura'),
    ('bibliotecas-e-livrarias', 'Lançamento de livro', 'lancamento-de-livro'),
    ('bibliotecas-e-livrarias', 'Clube do livro', 'clube-do-livro'),
    ('bibliotecas-e-livrarias', 'Estudo', 'estudo'),
    ('saraus-e-poesia', 'Slam', 'slam'),
    ('saraus-e-poesia', 'Sarau', 'sarau'),
    ('saraus-e-poesia', 'Microfone aberto', 'microfone-aberto'),
    ('saraus-e-poesia', 'Poesia', 'poesia'),
    ('oficinas-de-arte', 'Pintura', 'pintura'),
    ('oficinas-de-arte', 'Desenho', 'desenho'),
    ('oficinas-de-arte', 'Cerâmica', 'ceramica'),
    ('oficinas-de-arte', 'Iniciante', 'iniciante'),
    ('musica-e-instrumentos', 'Violão', 'violao'),
    ('musica-e-instrumentos', 'Canto', 'canto'),
    ('musica-e-instrumentos', 'Percussão', 'percussao'),
    ('musica-e-instrumentos', 'Aula experimental', 'aula-experimental'),
    ('aulas-de-danca', 'Forró', 'forro'),
    ('aulas-de-danca', 'Gafieira', 'gafieira'),
    ('aulas-de-danca', 'Zouk', 'zouk'),
    ('aulas-de-danca', 'Dança de salão', 'danca-de-salao'),
    ('cursos-de-culinaria', 'Culinária regional', 'culinaria-regional'),
    ('cursos-de-culinaria', 'Confeitaria', 'confeitaria'),
    ('cursos-de-culinaria', 'Churrasco', 'churrasco'),
    ('cursos-de-culinaria', 'Aula prática', 'aula-pratica'),
    ('corridas-de-rua', '5K', '5k'),
    ('corridas-de-rua', '10K', '10k'),
    ('corridas-de-rua', 'Meia maratona', 'meia-maratona'),
    ('corridas-de-rua', 'Kit atleta', 'kit-atleta'),
    ('grupos-de-corrida', 'Assessoria', 'assessoria'),
    ('grupos-de-corrida', 'Treino coletivo', 'treino-coletivo'),
    ('grupos-de-corrida', 'Iniciantes', 'iniciantes'),
    ('grupos-de-corrida', 'Madrugada', 'madrugada'),
    ('pedal-urbano', 'Ciclovia', 'ciclovia'),
    ('pedal-urbano', 'Pedal noturno', 'pedal-noturno'),
    ('pedal-urbano', 'Grupo de pedal', 'grupo-de-pedal'),
    ('pedal-urbano', 'Bike compartilhada', 'bike-compartilhada'),
    ('ciclismo-de-estrada', 'Speed', 'speed'),
    ('ciclismo-de-estrada', 'Estrada', 'estrada'),
    ('ciclismo-de-estrada', 'Pelotão', 'pelotao'),
    ('ciclismo-de-estrada', 'Prova', 'prova'),
    ('stand-up-paddle', 'SUP', 'sup'),
    ('stand-up-paddle', 'Aula', 'aula'),
    ('stand-up-paddle', 'Aluguel de prancha', 'aluguel-de-prancha'),
    ('stand-up-paddle', 'Pôr do sol', 'por-do-sol'),
    ('caiaque-e-canoagem', 'Caiaque', 'caiaque'),
    ('caiaque-e-canoagem', 'Canoagem', 'canoagem'),
    ('caiaque-e-canoagem', 'Remada', 'remada'),
    ('caiaque-e-canoagem', 'Rio', 'rio'),
    ('natacao-em-aguas-abertas', 'Águas abertas', 'aguas-abertas'),
    ('natacao-em-aguas-abertas', 'Travessia', 'travessia'),
    ('natacao-em-aguas-abertas', 'Treino', 'treino'),
    ('natacao-em-aguas-abertas', 'Segurança', 'seguranca'),
    ('clubes-e-piscinas', 'Clube', 'clube'),
    ('clubes-e-piscinas', 'Piscina', 'piscina'),
    ('clubes-e-piscinas', 'Day use', 'day-use'),
    ('clubes-e-piscinas', 'Sócio', 'socio'),
    ('futebol', 'Arena Pantanal', 'arena-pantanal'),
    ('futebol', 'Ingresso', 'ingresso'),
    ('futebol', 'Pelada', 'pelada'),
    ('futebol', 'Society', 'society'),
    ('quadras-e-areia', 'Beach tennis', 'beach-tennis'),
    ('quadras-e-areia', 'Futevôlei', 'futevolei'),
    ('quadras-e-areia', 'Vôlei de praia', 'volei-de-praia'),
    ('quadras-e-areia', 'Basquete', 'basquete'),
    ('lutas-e-mma', 'MMA', 'mma'),
    ('lutas-e-mma', 'Jiu-jitsu', 'jiu-jitsu'),
    ('lutas-e-mma', 'Boxe', 'boxe'),
    ('lutas-e-mma', 'Muay thai', 'muay-thai'),
    ('games-e-esports', 'eSports', 'esports'),
    ('games-e-esports', 'Campeonato', 'campeonato'),
    ('games-e-esports', 'Fliperama', 'fliperama'),
    ('games-e-esports', 'Board games', 'board-games'),
    ('parques-aquaticos', 'Toboágua', 'toboagua'),
    ('parques-aquaticos', 'Piscina de ondas', 'piscina-de-ondas'),
    ('parques-aquaticos', 'Família', 'familia'),
    ('parques-aquaticos', 'Ingresso', 'ingresso'),
    ('pesque-pague', 'Tanque', 'tanque'),
    ('pesque-pague', 'Pesca em família', 'pesca-em-familia'),
    ('pesque-pague', 'Peixe assado', 'peixe-assado'),
    ('pesque-pague', 'Aluguel de vara', 'aluguel-de-vara'),
    ('kart-paintball-e-boliche', 'Kart', 'kart'),
    ('kart-paintball-e-boliche', 'Paintball', 'paintball'),
    ('kart-paintball-e-boliche', 'Boliche', 'boliche'),
    ('kart-paintball-e-boliche', 'Laser tag', 'laser-tag'),
    ('parques-e-playgrounds', 'Playground', 'playground'),
    ('parques-e-playgrounds', 'Sombra', 'sombra'),
    ('parques-e-playgrounds', 'Espaço aberto', 'espaco-aberto'),
    ('parques-e-playgrounds', 'Gratuito', 'gratuito'),
    ('zoologico-e-fauna', 'Zoológico', 'zoologico'),
    ('zoologico-e-fauna', 'Animais silvestres', 'animais-silvestres'),
    ('zoologico-e-fauna', 'Educação ambiental', 'educacao-ambiental'),
    ('zoologico-e-fauna', 'Visita guiada', 'visita-guiada'),
    ('fazendinhas', 'Fazendinha', 'fazendinha'),
    ('fazendinhas', 'Animais', 'animais'),
    ('fazendinhas', 'Passeio a cavalo', 'passeio-a-cavalo'),
    ('fazendinhas', 'Pomar', 'pomar'),
    ('ciencia-e-descoberta', 'Interativo', 'interativo'),
    ('ciencia-e-descoberta', 'Planetário', 'planetario'),
    ('ciencia-e-descoberta', 'Experiências', 'experiencias'),
    ('ciencia-e-descoberta', 'Educativo', 'educativo'),
    ('contacao-de-historias', 'Contação', 'contacao'),
    ('contacao-de-historias', 'Leitura', 'leitura'),
    ('contacao-de-historias', 'Biblioteca', 'biblioteca'),
    ('contacao-de-historias', 'Gratuito', 'gratuito'),
    ('oficinas-infantis', 'Oficina', 'oficina'),
    ('oficinas-infantis', 'Arte', 'arte'),
    ('oficinas-infantis', 'Culinária kids', 'culinaria-kids'),
    ('oficinas-infantis', 'Ciência', 'ciencia'),
    ('festas-e-buffets-infantis', 'Buffet', 'buffet'),
    ('festas-e-buffets-infantis', 'Aniversário', 'aniversario'),
    ('festas-e-buffets-infantis', 'Recreação', 'recreacao'),
    ('festas-e-buffets-infantis', 'Decoração', 'decoracao'),
    ('colonia-de-ferias', 'Férias escolares', 'ferias-escolares'),
    ('colonia-de-ferias', 'Recreação', 'recreacao'),
    ('colonia-de-ferias', 'Esportes', 'esportes'),
    ('colonia-de-ferias', 'Meio período', 'meio-periodo'),
    ('espaco-kids', 'Brinquedoteca', 'brinquedoteca'),
    ('espaco-kids', 'Monitor', 'monitor'),
    ('espaco-kids', 'Parquinho', 'parquinho'),
    ('espaco-kids', 'Seguro', 'seguro'),
    ('cardapio-infantil', 'Menu kids', 'menu-kids'),
    ('cardapio-infantil', 'Porção infantil', 'porcao-infantil'),
    ('cardapio-infantil', 'Saudável', 'saudavel'),
    ('cardapio-infantil', 'Sobremesa', 'sobremesa'),
    ('feiras-livres', 'Hortifrúti', 'hortifruti'),
    ('feiras-livres', 'Feira do Porto', 'feira-do-porto'),
    ('feiras-livres', 'Pastel', 'pastel'),
    ('feiras-livres', 'Madrugada', 'madrugada'),
    ('feiras-de-artesanato', 'Artesanato', 'artesanato'),
    ('feiras-de-artesanato', 'Feito à mão', 'feito-a-mao'),
    ('feiras-de-artesanato', 'Artesão local', 'artesao-local'),
    ('feiras-de-artesanato', 'Presentes', 'presentes'),
    ('feiras-organicas', 'Orgânico', 'organico'),
    ('feiras-organicas', 'Agricultura familiar', 'agricultura-familiar'),
    ('feiras-organicas', 'Direto do produtor', 'direto-do-produtor'),
    ('feiras-organicas', 'Sem agrotóxico', 'sem-agrotoxico'),
    ('brechos-e-feiras-vintage', 'Brechó', 'brecho'),
    ('brechos-e-feiras-vintage', 'Vintage', 'vintage'),
    ('brechos-e-feiras-vintage', 'Vinil', 'vinil'),
    ('brechos-e-feiras-vintage', 'Antiguidades', 'antiguidades'),
    ('shoppings', 'Praça de alimentação', 'praca-de-alimentacao'),
    ('shoppings', 'Estacionamento', 'estacionamento'),
    ('shoppings', 'Cinema', 'cinema'),
    ('shoppings', 'Lojas', 'lojas'),
    ('lembrancas-e-souvenirs', 'Souvenir', 'souvenir'),
    ('lembrancas-e-souvenirs', 'Lembrancinha', 'lembrancinha'),
    ('lembrancas-e-souvenirs', 'Viola de cocho em miniatura', 'viola-de-cocho-em-miniatura'),
    ('lembrancas-e-souvenirs', 'Camiseta', 'camiseta'),
    ('emporios-e-produtos-regionais', 'Pequi', 'pequi'),
    ('emporios-e-produtos-regionais', 'Doces caseiros', 'doces-caseiros'),
    ('emporios-e-produtos-regionais', 'Licor', 'licor'),
    ('emporios-e-produtos-regionais', 'Cachaça', 'cachaca'),
    ('marcas-locais', 'Moda autoral', 'moda-autoral'),
    ('marcas-locais', 'Acessórios', 'acessorios'),
    ('marcas-locais', 'Estampa regional', 'estampa-regional'),
    ('marcas-locais', 'Sustentável', 'sustentavel'),
    ('atelies', 'Sob medida', 'sob-medida'),
    ('atelies', 'Joalheria', 'joalheria'),
    ('atelies', 'Costura', 'costura'),
    ('atelies', 'Design', 'design'),
    ('bazares-e-pop-ups', 'Pop-up', 'pop-up'),
    ('bazares-e-pop-ups', 'Bazar', 'bazar'),
    ('bazares-e-pop-ups', 'Temporário', 'temporario'),
    ('bazares-e-pop-ups', 'Coletivo', 'coletivo'),
    ('hoteis-em-cuiaba', 'Centro', 'centro'),
    ('hoteis-em-cuiaba', 'Aeroporto', 'aeroporto'),
    ('hoteis-em-cuiaba', 'Café da manhã', 'cafe-da-manha'),
    ('hoteis-em-cuiaba', 'Executivo', 'executivo'),
    ('pousadas-na-chapada', 'Vila', 'vila'),
    ('pousadas-na-chapada', 'Charme', 'charme'),
    ('pousadas-na-chapada', 'Lareira', 'lareira'),
    ('pousadas-na-chapada', 'Vista da serra', 'vista-da-serra'),
    ('pousadas-no-pantanal', 'Beira de rio', 'beira-de-rio'),
    ('pousadas-no-pantanal', 'Transpantaneira', 'transpantaneira'),
    ('pousadas-no-pantanal', 'Pensão completa', 'pensao-completa'),
    ('pousadas-no-pantanal', 'Passeios inclusos', 'passeios-inclusos'),
    ('resorts-e-hoteis-fazenda', 'Resort', 'resort'),
    ('resorts-e-hoteis-fazenda', 'Hotel-fazenda', 'hotel-fazenda'),
    ('resorts-e-hoteis-fazenda', 'Piscina', 'piscina'),
    ('resorts-e-hoteis-fazenda', 'Recreação', 'recreacao'),
    ('chales-e-cabanas', 'Chalé', 'chale'),
    ('chales-e-cabanas', 'Cabana', 'cabana'),
    ('chales-e-cabanas', 'Hidromassagem', 'hidromassagem'),
    ('chales-e-cabanas', 'Casal', 'casal'),
    ('hostels', 'Quarto compartilhado', 'quarto-compartilhado'),
    ('hostels', 'Econômico', 'economico'),
    ('hostels', 'Mochileiro', 'mochileiro'),
    ('hostels', 'Cozinha coletiva', 'cozinha-coletiva'),
    ('casas-e-chacaras-de-temporada', 'Casa inteira', 'casa-inteira'),
    ('casas-e-chacaras-de-temporada', 'Chácara', 'chacara'),
    ('casas-e-chacaras-de-temporada', 'Piscina', 'piscina'),
    ('casas-e-chacaras-de-temporada', 'Grupo', 'grupo'),
    ('day-use-em-hoteis-e-resorts', 'Piscina', 'piscina'),
    ('day-use-em-hoteis-e-resorts', 'Almoço incluso', 'almoco-incluso'),
    ('day-use-em-hoteis-e-resorts', 'Um dia', 'um-dia'),
    ('day-use-em-hoteis-e-resorts', 'Estrutura completa', 'estrutura-completa'),
    ('day-use-em-pousadas-e-chacaras', 'Chácara', 'chacara'),
    ('day-use-em-pousadas-e-chacaras', 'Pousada', 'pousada'),
    ('day-use-em-pousadas-e-chacaras', 'Natureza', 'natureza'),
    ('day-use-em-pousadas-e-chacaras', 'Perto de Cuiabá', 'perto-de-cuiaba'),
    ('spas-e-massagens', 'Massagem', 'massagem'),
    ('spas-e-massagens', 'Day spa', 'day-spa'),
    ('spas-e-massagens', 'Pedras quentes', 'pedras-quentes'),
    ('spas-e-massagens', 'Casal', 'casal'),
    ('aguas-termais', 'Águas termais', 'aguas-termais'),
    ('aguas-termais', 'Piscina natural', 'piscina-natural'),
    ('aguas-termais', 'Relaxamento', 'relaxamento'),
    ('aguas-termais', 'Hotel', 'hotel'),
    ('yoga', 'Hatha', 'hatha'),
    ('yoga', 'Vinyasa', 'vinyasa'),
    ('yoga', 'Yoga no parque', 'yoga-no-parque'),
    ('yoga', 'Aula experimental', 'aula-experimental'),
    ('meditacao', 'Meditação guiada', 'meditacao-guiada'),
    ('meditacao', 'Mindfulness', 'mindfulness'),
    ('meditacao', 'Grupo', 'grupo'),
    ('meditacao', 'Respiração', 'respiracao'),
    ('retiros-na-natureza', 'Retiro', 'retiro'),
    ('retiros-na-natureza', 'Silêncio', 'silencio'),
    ('retiros-na-natureza', 'Chapada', 'chapada'),
    ('retiros-na-natureza', 'Detox digital', 'detox-digital'),
    ('academias-e-estudios', 'Musculação', 'musculacao'),
    ('academias-e-estudios', 'Crossfit', 'crossfit'),
    ('academias-e-estudios', 'Estúdio', 'estudio'),
    ('academias-e-estudios', 'Diária', 'diaria'),
    ('treino-funcional-ao-ar-livre', 'Funcional', 'funcional'),
    ('treino-funcional-ao-ar-livre', 'Parque', 'parque'),
    ('treino-funcional-ao-ar-livre', 'Grupo', 'grupo'),
    ('treino-funcional-ao-ar-livre', 'Manhã cedo', 'manha-cedo'),
    ('pilates', 'Pilates solo', 'pilates-solo'),
    ('pilates', 'Aparelhos', 'aparelhos'),
    ('pilates', 'Postura', 'postura'),
    ('pilates', 'Reabilitação', 'reabilitacao'),
    ('um-dia-em-cuiaba', 'Manhã', 'manha'),
    ('um-dia-em-cuiaba', 'Almoço cuiabano', 'almoco-cuiabano'),
    ('um-dia-em-cuiaba', 'Pôr do sol na orla', 'por-do-sol-na-orla'),
    ('um-dia-em-cuiaba', 'Noite', 'noite'),
    ('fim-de-semana-na-chapada', 'Dois dias', 'dois-dias'),
    ('fim-de-semana-na-chapada', 'Cachoeiras', 'cachoeiras'),
    ('fim-de-semana-na-chapada', 'Mirantes', 'mirantes'),
    ('fim-de-semana-na-chapada', 'Onde comer', 'onde-comer'),
    ('tres-dias-no-pantanal', 'Três dias', 'tres-dias'),
    ('tres-dias-no-pantanal', 'Safári', 'safari'),
    ('tres-dias-no-pantanal', 'Barco', 'barco'),
    ('tres-dias-no-pantanal', 'Pousada', 'pousada'),
    ('roteiro-gastronomico', 'Peixe', 'peixe'),
    ('roteiro-gastronomico', 'Doces típicos', 'doces-tipicos'),
    ('roteiro-gastronomico', 'Chá com bolo', 'cha-com-bolo'),
    ('roteiro-gastronomico', 'Feira', 'feira'),
    ('melhor-epoca-para-visitar', 'Seca', 'seca'),
    ('melhor-epoca-para-visitar', 'Chuva', 'chuva'),
    ('melhor-epoca-para-visitar', 'Calor', 'calor'),
    ('melhor-epoca-para-visitar', 'Alta temporada', 'alta-temporada'),
    ('como-chegar-e-transporte', 'Aeroporto', 'aeroporto'),
    ('como-chegar-e-transporte', 'Rodoviária', 'rodoviaria'),
    ('como-chegar-e-transporte', 'Aluguel de carro', 'aluguel-de-carro'),
    ('como-chegar-e-transporte', 'Aplicativo', 'aplicativo'),
    ('calor-e-seguranca', 'Hidratação', 'hidratacao'),
    ('calor-e-seguranca', 'Protetor solar', 'protetor-solar'),
    ('calor-e-seguranca', 'Repelente', 'repelente'),
    ('calor-e-seguranca', 'Calor extremo', 'calor-extremo'),
    ('economize', 'Gratuito', 'gratuito'),
    ('economize', 'Meia-entrada', 'meia-entrada'),
    ('economize', 'Promoção', 'promocao'),
    ('economize', 'Cupom', 'cupom'),
    ('lugares-escondidos', 'Pouco conhecido', 'pouco-conhecido'),
    ('lugares-escondidos', 'Sem aglomeração', 'sem-aglomeracao'),
    ('lugares-escondidos', 'Segredo local', 'segredo-local'),
    ('lugares-escondidos', 'Tranquilo', 'tranquilo'),
    ('programas-baratos', 'Até R$ 50', 'ate-r-50'),
    ('programas-baratos', 'Gratuito', 'gratuito'),
    ('programas-baratos', 'Econômico', 'economico'),
    ('programas-baratos', 'Com amigos', 'com-amigos'),
    ('programas-romanticos', 'Casal', 'casal'),
    ('programas-romanticos', 'Pôr do sol', 'por-do-sol'),
    ('programas-romanticos', 'Jantar', 'jantar'),
    ('programas-romanticos', 'Surpresa', 'surpresa'),
    ('pet-friendly', 'Pet friendly', 'pet-friendly'),
    ('pet-friendly', 'Cachorro', 'cachorro'),
    ('pet-friendly', 'Área pet', 'area-pet'),
    ('pet-friendly', 'Água para pet', 'agua-para-pet')
) AS v(sub_slug, name, slug)
JOIN public.categories_sub s ON s.slug = v.sub_slug
JOIN LATERAL (
    SELECT uid FROM auth.users WHERE is_root = true ORDER BY created_at ASC LIMIT 1
) AS u(uid) ON true
JOIN LATERAL (
    SELECT tn.uid FROM auth.tenants tn WHERE tn.owner_uid = u.uid ORDER BY tn.created_at ASC LIMIT 1
) AS t(uid) ON true
ON CONFLICT ON CONSTRAINT categories_sub_tags_sub_slug_key DO UPDATE SET
  name = EXCLUDED.name, category_id = EXCLUDED.category_id, updated_at = now();

-- 5) Vínculos extras: categoria listada também em outros grupos (categories_group_link) --------
INSERT INTO public.categories_group_link (category_id, category_group_id, tenant_id, created_by)
SELECT c.id, g.id, t.uid, u.uid
FROM (VALUES
    ('shows-e-musica-ao-vivo', 'bares-e-vida-noturna'),
    ('festas-tradicionais-e-religiosas', 'cultura-e-arte'),
    ('festivais-e-exposicoes', 'restaurantes-e-gastronomia'),
    ('teatro', 'eventos'),
    ('teatro', 'cultura-e-arte'),
    ('humor-e-espetaculos', 'eventos'),
    ('cinema', 'eventos'),
    ('cachoeiras-e-rios', 'trilhas-e-aventura'),
    ('cachoeiras-e-rios', 'turismo'),
    ('pantanal-e-vida-selvagem', 'turismo'),
    ('parques-e-areas-verdes', 'familia-e-criancas'),
    ('parques-e-areas-verdes', 'esportes-e-lazer'),
    ('culinaria-cuiabana-e-pantaneira', 'turismo'),
    ('happy-hour-e-petiscos', 'restaurantes-e-gastronomia'),
    ('espacos-culturais', 'eventos'),
    ('cultura-popular-e-artesanato', 'compras-e-feiras'),
    ('feiras', 'turismo'),
    ('diversao-ao-ar-livre', 'familia-e-criancas'),
    ('day-use', 'esportes-e-lazer'),
    ('guias-e-agencias', 'turismo'),
    ('achados-locais', 'turismo')
) AS v(category_slug, group_slug)
JOIN public.categories c ON c.slug = v.category_slug
JOIN public.categories_group g ON g.slug = v.group_slug
JOIN LATERAL (
    SELECT uid FROM auth.users WHERE is_root = true ORDER BY created_at ASC LIMIT 1
) AS u(uid) ON true
JOIN LATERAL (
    SELECT tn.uid FROM auth.tenants tn WHERE tn.owner_uid = u.uid ORDER BY tn.created_at ASC LIMIT 1
) AS t(uid) ON true
ON CONFLICT ON CONSTRAINT categories_group_link_unique DO NOTHING;

COMMIT;

NOTIFY pgrst, 'reload schema';
